// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/American-Cloud/americancloud-sdk-go/internal"
	big "math/big"
)

var (
	createDatabaseClusterDtoFieldUserClusterID    = big.NewInt(1 << 0)
	createDatabaseClusterDtoFieldDbClusterName    = big.NewInt(1 << 1)
	createDatabaseClusterDtoFieldSSHKey           = big.NewInt(1 << 2)
	createDatabaseClusterDtoFieldOfferingID       = big.NewInt(1 << 3)
	createDatabaseClusterDtoFieldOfferingName     = big.NewInt(1 << 4)
	createDatabaseClusterDtoFieldRegionID         = big.NewInt(1 << 5)
	createDatabaseClusterDtoFieldTier             = big.NewInt(1 << 6)
	createDatabaseClusterDtoFieldAvailabilityType = big.NewInt(1 << 7)
	createDatabaseClusterDtoFieldStorageGb        = big.NewInt(1 << 8)
	createDatabaseClusterDtoFieldNetworkConfig    = big.NewInt(1 << 9)
	createDatabaseClusterDtoFieldRestore          = big.NewInt(1 << 10)
)

type CreateDatabaseClusterDto struct {
	// Identifier of an existing infrastructure cluster to deploy the database on. Omit to provision new infrastructure.
	UserClusterID *string `json:"userClusterId,omitempty" url:"-"`
	// Database cluster name. Must comply with Kubernetes naming rules.
	DbClusterName string `json:"dbClusterName" url:"-"`
	// SSH key authorized for access to the cluster. Required when creating a new cluster; omit only when deploying onto an existing `userClusterId`.
	SSHKey *string `json:"sshKey,omitempty" url:"-"`
	// Identifier of the database offering to use.
	OfferingID *string `json:"offeringId,omitempty" url:"-"`
	// Name of the database offering. Alternative to `offeringId` for selecting an offering.
	OfferingName *string `json:"offeringName,omitempty" url:"-"`
	// Identifier of the region the cluster will run in.
	RegionID string `json:"regionId" url:"-"`
	// Infrastructure tier that determines per-node CPU and memory.
	Tier string `json:"tier" url:"-"`
	// Availability mode for the cluster.
	AvailabilityType CreateDatabaseClusterDtoAvailabilityType `json:"availabilityType" url:"-"`
	// Storage capacity allocated to the cluster, in gigabytes.
	StorageGb *int `json:"storageGb,omitempty" url:"-"`
	// Network the cluster will attach to. Required when creating a new cluster; omit only when deploying onto an existing `userClusterId`.
	NetworkConfig *CreateDatabaseClusterDtoNetworkConfig `json:"networkConfig,omitempty" url:"-"`
	// Restore-from-backup configuration. Provide to bootstrap the new cluster from an existing backup.
	Restore *CreateClusterRestoreDto `json:"restore,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateDatabaseClusterDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetUserClusterID sets the UserClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetUserClusterID(userClusterID *string) {
	c.UserClusterID = userClusterID
	c.require(createDatabaseClusterDtoFieldUserClusterID)
}

// SetDbClusterName sets the DbClusterName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetDbClusterName(dbClusterName string) {
	c.DbClusterName = dbClusterName
	c.require(createDatabaseClusterDtoFieldDbClusterName)
}

// SetSSHKey sets the SSHKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetSSHKey(sshKey *string) {
	c.SSHKey = sshKey
	c.require(createDatabaseClusterDtoFieldSSHKey)
}

// SetOfferingID sets the OfferingID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetOfferingID(offeringID *string) {
	c.OfferingID = offeringID
	c.require(createDatabaseClusterDtoFieldOfferingID)
}

// SetOfferingName sets the OfferingName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetOfferingName(offeringName *string) {
	c.OfferingName = offeringName
	c.require(createDatabaseClusterDtoFieldOfferingName)
}

// SetRegionID sets the RegionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetRegionID(regionID string) {
	c.RegionID = regionID
	c.require(createDatabaseClusterDtoFieldRegionID)
}

// SetTier sets the Tier field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetTier(tier string) {
	c.Tier = tier
	c.require(createDatabaseClusterDtoFieldTier)
}

// SetAvailabilityType sets the AvailabilityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetAvailabilityType(availabilityType CreateDatabaseClusterDtoAvailabilityType) {
	c.AvailabilityType = availabilityType
	c.require(createDatabaseClusterDtoFieldAvailabilityType)
}

// SetStorageGb sets the StorageGb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetStorageGb(storageGb *int) {
	c.StorageGb = storageGb
	c.require(createDatabaseClusterDtoFieldStorageGb)
}

// SetNetworkConfig sets the NetworkConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetNetworkConfig(networkConfig *CreateDatabaseClusterDtoNetworkConfig) {
	c.NetworkConfig = networkConfig
	c.require(createDatabaseClusterDtoFieldNetworkConfig)
}

// SetRestore sets the Restore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDatabaseClusterDto) SetRestore(restore *CreateClusterRestoreDto) {
	c.Restore = restore
	c.require(createDatabaseClusterDtoFieldRestore)
}

func (c *CreateDatabaseClusterDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDatabaseClusterDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateDatabaseClusterDto(body)
	return nil
}

func (c *CreateDatabaseClusterDto) MarshalJSON() ([]byte, error) {
	type embed CreateDatabaseClusterDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteDatabasesRequestFieldClusterID = big.NewInt(1 << 0)
)

type DeleteDatabasesRequest struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteDatabasesRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteDatabasesRequest) SetClusterID(clusterID string) {
	d.ClusterID = clusterID
	d.require(deleteDatabasesRequestFieldClusterID)
}

var (
	deleteLoadBalancerDatabasesRequestFieldClusterID = big.NewInt(1 << 0)
	deleteLoadBalancerDatabasesRequestFieldType      = big.NewInt(1 << 1)
)

type DeleteLoadBalancerDatabasesRequest struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`
	// Load balancer type
	Type DeleteLoadBalancerDatabasesRequestType `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteLoadBalancerDatabasesRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteLoadBalancerDatabasesRequest) SetClusterID(clusterID string) {
	d.ClusterID = clusterID
	d.require(deleteLoadBalancerDatabasesRequestFieldClusterID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteLoadBalancerDatabasesRequest) SetType(type_ DeleteLoadBalancerDatabasesRequestType) {
	d.Type = type_
	d.require(deleteLoadBalancerDatabasesRequestFieldType)
}

var (
	getConnectionDatabasesRequestFieldClusterID       = big.NewInt(1 << 0)
	getConnectionDatabasesRequestFieldIncludePassword = big.NewInt(1 << 1)
)

type GetConnectionDatabasesRequest struct {
	// Database cluster ID
	ClusterID       string `json:"-" url:"-"`
	IncludePassword string `json:"-" url:"includePassword"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetConnectionDatabasesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConnectionDatabasesRequest) SetClusterID(clusterID string) {
	g.ClusterID = clusterID
	g.require(getConnectionDatabasesRequestFieldClusterID)
}

// SetIncludePassword sets the IncludePassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConnectionDatabasesRequest) SetIncludePassword(includePassword string) {
	g.IncludePassword = includePassword
	g.require(getConnectionDatabasesRequestFieldIncludePassword)
}

var (
	getCostEstimateDatabasesRequestFieldOfferingID       = big.NewInt(1 << 0)
	getCostEstimateDatabasesRequestFieldUserClusterID    = big.NewInt(1 << 1)
	getCostEstimateDatabasesRequestFieldAvailabilityType = big.NewInt(1 << 2)
	getCostEstimateDatabasesRequestFieldStorageGb        = big.NewInt(1 << 3)
	getCostEstimateDatabasesRequestFieldTier             = big.NewInt(1 << 4)
	getCostEstimateDatabasesRequestFieldDbClusterID      = big.NewInt(1 << 5)
)

type GetCostEstimateDatabasesRequest struct {
	// Database offering ID
	OfferingID string `json:"-" url:"-"`
	// Existing infrastructure cluster ID for marginal cost calculation
	UserClusterID *string `json:"-" url:"user_cluster_id,omitempty"`
	// Availability type: "single-node" or "data-redundancy"
	AvailabilityType *string `json:"-" url:"availability_type,omitempty"`
	// Custom storage size in GB
	StorageGb *string `json:"-" url:"storage_gb,omitempty"`
	// Infrastructure tier: "standard" or "premium"
	Tier *string `json:"-" url:"tier,omitempty"`
	// Database cluster ID for resize cost estimates (replaces workload instead of adding)
	DbClusterID *string `json:"-" url:"db_cluster_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCostEstimateDatabasesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetOfferingID sets the OfferingID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCostEstimateDatabasesRequest) SetOfferingID(offeringID string) {
	g.OfferingID = offeringID
	g.require(getCostEstimateDatabasesRequestFieldOfferingID)
}

// SetUserClusterID sets the UserClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCostEstimateDatabasesRequest) SetUserClusterID(userClusterID *string) {
	g.UserClusterID = userClusterID
	g.require(getCostEstimateDatabasesRequestFieldUserClusterID)
}

// SetAvailabilityType sets the AvailabilityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCostEstimateDatabasesRequest) SetAvailabilityType(availabilityType *string) {
	g.AvailabilityType = availabilityType
	g.require(getCostEstimateDatabasesRequestFieldAvailabilityType)
}

// SetStorageGb sets the StorageGb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCostEstimateDatabasesRequest) SetStorageGb(storageGb *string) {
	g.StorageGb = storageGb
	g.require(getCostEstimateDatabasesRequestFieldStorageGb)
}

// SetTier sets the Tier field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCostEstimateDatabasesRequest) SetTier(tier *string) {
	g.Tier = tier
	g.require(getCostEstimateDatabasesRequestFieldTier)
}

// SetDbClusterID sets the DbClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCostEstimateDatabasesRequest) SetDbClusterID(dbClusterID *string) {
	g.DbClusterID = dbClusterID
	g.require(getCostEstimateDatabasesRequestFieldDbClusterID)
}

var (
	getDatabasesRequestFieldClusterID = big.NewInt(1 << 0)
)

type GetDatabasesRequest struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetDatabasesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDatabasesRequest) SetClusterID(clusterID string) {
	g.ClusterID = clusterID
	g.require(getDatabasesRequestFieldClusterID)
}

var (
	getOperationsDatabasesRequestFieldClusterID = big.NewInt(1 << 0)
)

type GetOperationsDatabasesRequest struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetOperationsDatabasesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOperationsDatabasesRequest) SetClusterID(clusterID string) {
	g.ClusterID = clusterID
	g.require(getOperationsDatabasesRequestFieldClusterID)
}

var (
	getStatusDatabasesRequestFieldClusterID = big.NewInt(1 << 0)
)

type GetStatusDatabasesRequest struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetStatusDatabasesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetStatusDatabasesRequest) SetClusterID(clusterID string) {
	g.ClusterID = clusterID
	g.require(getStatusDatabasesRequestFieldClusterID)
}

var (
	listDatabasesRequestFieldUserClusterID = big.NewInt(1 << 0)
	listDatabasesRequestFieldPage          = big.NewInt(1 << 1)
	listDatabasesRequestFieldPageSize      = big.NewInt(1 << 2)
)

type ListDatabasesRequest struct {
	// Filter by infrastructure cluster ID
	UserClusterID *string `json:"-" url:"user_cluster_id,omitempty"`
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListDatabasesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetUserClusterID sets the UserClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDatabasesRequest) SetUserClusterID(userClusterID *string) {
	l.UserClusterID = userClusterID
	l.require(listDatabasesRequestFieldUserClusterID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDatabasesRequest) SetPage(page *int) {
	l.Page = page
	l.require(listDatabasesRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDatabasesRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listDatabasesRequestFieldPageSize)
}

var (
	modifyLoadBalancerRequestDtoFieldClusterID      = big.NewInt(1 << 0)
	modifyLoadBalancerRequestDtoFieldType           = big.NewInt(1 << 1)
	modifyLoadBalancerRequestDtoFieldCidr           = big.NewInt(1 << 2)
	modifyLoadBalancerRequestDtoFieldLoadBalancerIP = big.NewInt(1 << 3)
)

type ModifyLoadBalancerRequestDto struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`
	// Load balancer type
	Type ModifyLoadBalancerDatabasesRequestType `json:"-" url:"-"`
	// CIDR range allowed to reach the load balancer.
	Cidr *string `json:"cidr,omitempty" url:"-"`
	// Pre-allocated private IP address for the load balancer.
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *ModifyLoadBalancerRequestDto) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModifyLoadBalancerRequestDto) SetClusterID(clusterID string) {
	m.ClusterID = clusterID
	m.require(modifyLoadBalancerRequestDtoFieldClusterID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModifyLoadBalancerRequestDto) SetType(type_ ModifyLoadBalancerDatabasesRequestType) {
	m.Type = type_
	m.require(modifyLoadBalancerRequestDtoFieldType)
}

// SetCidr sets the Cidr field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModifyLoadBalancerRequestDto) SetCidr(cidr *string) {
	m.Cidr = cidr
	m.require(modifyLoadBalancerRequestDtoFieldCidr)
}

// SetLoadBalancerIP sets the LoadBalancerIP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModifyLoadBalancerRequestDto) SetLoadBalancerIP(loadBalancerIP *string) {
	m.LoadBalancerIP = loadBalancerIP
	m.require(modifyLoadBalancerRequestDtoFieldLoadBalancerIP)
}

func (m *ModifyLoadBalancerRequestDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ModifyLoadBalancerRequestDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = ModifyLoadBalancerRequestDto(body)
	return nil
}

func (m *ModifyLoadBalancerRequestDto) MarshalJSON() ([]byte, error) {
	type embed ModifyLoadBalancerRequestDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	resizeDatabaseClusterDtoFieldClusterID  = big.NewInt(1 << 0)
	resizeDatabaseClusterDtoFieldOfferingID = big.NewInt(1 << 1)
	resizeDatabaseClusterDtoFieldStorageGb  = big.NewInt(1 << 2)
)

type ResizeDatabaseClusterDto struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`
	// Identifier of the target database offering to resize to.
	OfferingID string `json:"offeringId" url:"-"`
	// New storage capacity for the cluster, in gigabytes.
	StorageGb *int `json:"storageGb,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ResizeDatabaseClusterDto) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResizeDatabaseClusterDto) SetClusterID(clusterID string) {
	r.ClusterID = clusterID
	r.require(resizeDatabaseClusterDtoFieldClusterID)
}

// SetOfferingID sets the OfferingID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResizeDatabaseClusterDto) SetOfferingID(offeringID string) {
	r.OfferingID = offeringID
	r.require(resizeDatabaseClusterDtoFieldOfferingID)
}

// SetStorageGb sets the StorageGb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResizeDatabaseClusterDto) SetStorageGb(storageGb *int) {
	r.StorageGb = storageGb
	r.require(resizeDatabaseClusterDtoFieldStorageGb)
}

func (r *ResizeDatabaseClusterDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ResizeDatabaseClusterDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ResizeDatabaseClusterDto(body)
	return nil
}

func (r *ResizeDatabaseClusterDto) MarshalJSON() ([]byte, error) {
	type embed ResizeDatabaseClusterDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	startDatabasesRequestFieldClusterID = big.NewInt(1 << 0)
)

type StartDatabasesRequest struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StartDatabasesRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartDatabasesRequest) SetClusterID(clusterID string) {
	s.ClusterID = clusterID
	s.require(startDatabasesRequestFieldClusterID)
}

var (
	stopDatabasesRequestFieldClusterID = big.NewInt(1 << 0)
)

type StopDatabasesRequest struct {
	// Database cluster ID
	ClusterID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StopDatabasesRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetClusterID sets the ClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopDatabasesRequest) SetClusterID(clusterID string) {
	s.ClusterID = clusterID
	s.require(stopDatabasesRequestFieldClusterID)
}

type ClusterActionResponseDto struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClusterActionResponseDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ClusterActionResponseDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

func (c *ClusterActionResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ClusterActionResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClusterActionResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClusterActionResponseDto) MarshalJSON() ([]byte, error) {
	type embed ClusterActionResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ClusterActionResponseDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ClusterDetailResponseDto struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClusterDetailResponseDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ClusterDetailResponseDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

func (c *ClusterDetailResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ClusterDetailResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClusterDetailResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClusterDetailResponseDto) MarshalJSON() ([]byte, error) {
	type embed ClusterDetailResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ClusterDetailResponseDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ClusterStatusResponseDto struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClusterStatusResponseDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ClusterStatusResponseDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

func (c *ClusterStatusResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ClusterStatusResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClusterStatusResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClusterStatusResponseDto) MarshalJSON() ([]byte, error) {
	type embed ClusterStatusResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ClusterStatusResponseDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ConnectionInfoResponseDto struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionInfoResponseDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectionInfoResponseDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

func (c *ConnectionInfoResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionInfoResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionInfoResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionInfoResponseDto) MarshalJSON() ([]byte, error) {
	type embed ConnectionInfoResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectionInfoResponseDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateClusterResponseDto struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateClusterResponseDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateClusterResponseDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

func (c *CreateClusterResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateClusterResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateClusterResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateClusterResponseDto) MarshalJSON() ([]byte, error) {
	type embed CreateClusterResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateClusterResponseDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createClusterRestoreDtoFieldSourceClusterID    = big.NewInt(1 << 0)
	createClusterRestoreDtoFieldBackupName         = big.NewInt(1 << 1)
	createClusterRestoreDtoFieldRestorePointInTime = big.NewInt(1 << 2)
)

type CreateClusterRestoreDto struct {
	// Identifier of the source cluster to restore from.
	SourceClusterID string `json:"sourceClusterId" url:"sourceClusterId"`
	// Name of the backup to restore from on the source cluster.
	BackupName string `json:"backupName" url:"backupName"`
	// Point-in-time to restore to, in ISO 8601 format. Omit to restore to the backup timestamp.
	RestorePointInTime *string `json:"restorePointInTime,omitempty" url:"restorePointInTime,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateClusterRestoreDto) GetSourceClusterID() string {
	if c == nil {
		return ""
	}
	return c.SourceClusterID
}

func (c *CreateClusterRestoreDto) GetBackupName() string {
	if c == nil {
		return ""
	}
	return c.BackupName
}

func (c *CreateClusterRestoreDto) GetRestorePointInTime() *string {
	if c == nil {
		return nil
	}
	return c.RestorePointInTime
}

func (c *CreateClusterRestoreDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateClusterRestoreDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSourceClusterID sets the SourceClusterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateClusterRestoreDto) SetSourceClusterID(sourceClusterID string) {
	c.SourceClusterID = sourceClusterID
	c.require(createClusterRestoreDtoFieldSourceClusterID)
}

// SetBackupName sets the BackupName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateClusterRestoreDto) SetBackupName(backupName string) {
	c.BackupName = backupName
	c.require(createClusterRestoreDtoFieldBackupName)
}

// SetRestorePointInTime sets the RestorePointInTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateClusterRestoreDto) SetRestorePointInTime(restorePointInTime *string) {
	c.RestorePointInTime = restorePointInTime
	c.require(createClusterRestoreDtoFieldRestorePointInTime)
}

func (c *CreateClusterRestoreDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateClusterRestoreDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateClusterRestoreDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateClusterRestoreDto) MarshalJSON() ([]byte, error) {
	type embed CreateClusterRestoreDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateClusterRestoreDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type DbsCostEstimateResponseDto struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DbsCostEstimateResponseDto) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DbsCostEstimateResponseDto) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

func (d *DbsCostEstimateResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler DbsCostEstimateResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DbsCostEstimateResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DbsCostEstimateResponseDto) MarshalJSON() ([]byte, error) {
	type embed DbsCostEstimateResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DbsCostEstimateResponseDto) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	isolatedNetworkConfigDtoFieldNetworkID = big.NewInt(1 << 0)
	isolatedNetworkConfigDtoFieldZoneName  = big.NewInt(1 << 1)
)

type IsolatedNetworkConfigDto struct {
	// Identifier of the isolated network the cluster will attach to.
	NetworkID string `json:"networkId" url:"networkId"`
	// Zone name override for the cluster.
	ZoneName *string `json:"zoneName,omitempty" url:"zoneName,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IsolatedNetworkConfigDto) GetNetworkID() string {
	if i == nil {
		return ""
	}
	return i.NetworkID
}

func (i *IsolatedNetworkConfigDto) GetZoneName() *string {
	if i == nil {
		return nil
	}
	return i.ZoneName
}

func (i *IsolatedNetworkConfigDto) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IsolatedNetworkConfigDto) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IsolatedNetworkConfigDto) SetNetworkID(networkID string) {
	i.NetworkID = networkID
	i.require(isolatedNetworkConfigDtoFieldNetworkID)
}

// SetZoneName sets the ZoneName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IsolatedNetworkConfigDto) SetZoneName(zoneName *string) {
	i.ZoneName = zoneName
	i.require(isolatedNetworkConfigDtoFieldZoneName)
}

func (i *IsolatedNetworkConfigDto) UnmarshalJSON(data []byte) error {
	type unmarshaler IsolatedNetworkConfigDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IsolatedNetworkConfigDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IsolatedNetworkConfigDto) MarshalJSON() ([]byte, error) {
	type embed IsolatedNetworkConfigDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IsolatedNetworkConfigDto) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type RecentOperationsResponseDto struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RecentOperationsResponseDto) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RecentOperationsResponseDto) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

func (r *RecentOperationsResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler RecentOperationsResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RecentOperationsResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecentOperationsResponseDto) MarshalJSON() ([]byte, error) {
	type embed RecentOperationsResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RecentOperationsResponseDto) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	vpcNetworkConfigDtoFieldVpcID     = big.NewInt(1 << 0)
	vpcNetworkConfigDtoFieldNetworkID = big.NewInt(1 << 1)
	vpcNetworkConfigDtoFieldZoneName  = big.NewInt(1 << 2)
)

type VpcNetworkConfigDto struct {
	// Identifier of the VPC the cluster will attach to.
	VpcID string `json:"vpcId" url:"vpcId"`
	// Identifier of the network tier within the VPC the cluster will attach to.
	NetworkID string `json:"networkId" url:"networkId"`
	// Zone name override for the cluster.
	ZoneName *string `json:"zoneName,omitempty" url:"zoneName,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VpcNetworkConfigDto) GetVpcID() string {
	if v == nil {
		return ""
	}
	return v.VpcID
}

func (v *VpcNetworkConfigDto) GetNetworkID() string {
	if v == nil {
		return ""
	}
	return v.NetworkID
}

func (v *VpcNetworkConfigDto) GetZoneName() *string {
	if v == nil {
		return nil
	}
	return v.ZoneName
}

func (v *VpcNetworkConfigDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VpcNetworkConfigDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcID sets the VpcID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcNetworkConfigDto) SetVpcID(vpcID string) {
	v.VpcID = vpcID
	v.require(vpcNetworkConfigDtoFieldVpcID)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcNetworkConfigDto) SetNetworkID(networkID string) {
	v.NetworkID = networkID
	v.require(vpcNetworkConfigDtoFieldNetworkID)
}

// SetZoneName sets the ZoneName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcNetworkConfigDto) SetZoneName(zoneName *string) {
	v.ZoneName = zoneName
	v.require(vpcNetworkConfigDtoFieldZoneName)
}

func (v *VpcNetworkConfigDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VpcNetworkConfigDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VpcNetworkConfigDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VpcNetworkConfigDto) MarshalJSON() ([]byte, error) {
	type embed VpcNetworkConfigDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VpcNetworkConfigDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// Availability mode for the cluster.
type CreateDatabaseClusterDtoAvailabilityType string

const (
	CreateDatabaseClusterDtoAvailabilityTypeSingleNode     CreateDatabaseClusterDtoAvailabilityType = "single-node"
	CreateDatabaseClusterDtoAvailabilityTypeDataRedundancy CreateDatabaseClusterDtoAvailabilityType = "data-redundancy"
)

func NewCreateDatabaseClusterDtoAvailabilityTypeFromString(s string) (CreateDatabaseClusterDtoAvailabilityType, error) {
	switch s {
	case "single-node":
		return CreateDatabaseClusterDtoAvailabilityTypeSingleNode, nil
	case "data-redundancy":
		return CreateDatabaseClusterDtoAvailabilityTypeDataRedundancy, nil
	}
	var t CreateDatabaseClusterDtoAvailabilityType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateDatabaseClusterDtoAvailabilityType) Ptr() *CreateDatabaseClusterDtoAvailabilityType {
	return &c
}

// Network the cluster will attach to. Required when creating a new cluster; omit only when deploying onto an existing `userClusterId`.
type CreateDatabaseClusterDtoNetworkConfig struct {
	NetworkType string
	Isolated    *IsolatedNetworkConfigDto
	Vpc         *VpcNetworkConfigDto
}

func (c *CreateDatabaseClusterDtoNetworkConfig) GetNetworkType() string {
	if c == nil {
		return ""
	}
	return c.NetworkType
}

func (c *CreateDatabaseClusterDtoNetworkConfig) GetIsolated() *IsolatedNetworkConfigDto {
	if c == nil {
		return nil
	}
	return c.Isolated
}

func (c *CreateDatabaseClusterDtoNetworkConfig) GetVpc() *VpcNetworkConfigDto {
	if c == nil {
		return nil
	}
	return c.Vpc
}

func (c *CreateDatabaseClusterDtoNetworkConfig) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		NetworkType string `json:"networkType"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	c.NetworkType = unmarshaler.NetworkType
	if unmarshaler.NetworkType == "" {
		return fmt.Errorf("%T did not include discriminant networkType", c)
	}
	switch unmarshaler.NetworkType {
	case "isolated":
		value := new(IsolatedNetworkConfigDto)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.Isolated = value
	case "vpc":
		value := new(VpcNetworkConfigDto)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.Vpc = value
	}
	return nil
}

func (c CreateDatabaseClusterDtoNetworkConfig) MarshalJSON() ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	if c.Isolated != nil {
		return internal.MarshalJSONWithExtraProperty(c.Isolated, "networkType", "isolated")
	}
	if c.Vpc != nil {
		return internal.MarshalJSONWithExtraProperty(c.Vpc, "networkType", "vpc")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", c)
}

type CreateDatabaseClusterDtoNetworkConfigVisitor interface {
	VisitIsolated(*IsolatedNetworkConfigDto) error
	VisitVpc(*VpcNetworkConfigDto) error
}

func (c *CreateDatabaseClusterDtoNetworkConfig) Accept(visitor CreateDatabaseClusterDtoNetworkConfigVisitor) error {
	if c.Isolated != nil {
		return visitor.VisitIsolated(c.Isolated)
	}
	if c.Vpc != nil {
		return visitor.VisitVpc(c.Vpc)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", c)
}

func (c *CreateDatabaseClusterDtoNetworkConfig) validate() error {
	if c == nil {
		return fmt.Errorf("type %T is nil", c)
	}
	var fields []string
	if c.Isolated != nil {
		fields = append(fields, "isolated")
	}
	if c.Vpc != nil {
		fields = append(fields, "vpc")
	}
	if len(fields) == 0 {
		if c.NetworkType != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", c, c.NetworkType)
		}
		return fmt.Errorf("type %T is empty", c)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", c, fields)
	}
	if c.NetworkType != "" {
		field := fields[0]
		if c.NetworkType != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				c,
				c.NetworkType,
				c,
			)
		}
	}
	return nil
}

type DeleteLoadBalancerDatabasesRequestType string

const (
	DeleteLoadBalancerDatabasesRequestTypePublic  DeleteLoadBalancerDatabasesRequestType = "public"
	DeleteLoadBalancerDatabasesRequestTypePrivate DeleteLoadBalancerDatabasesRequestType = "private"
)

func NewDeleteLoadBalancerDatabasesRequestTypeFromString(s string) (DeleteLoadBalancerDatabasesRequestType, error) {
	switch s {
	case "public":
		return DeleteLoadBalancerDatabasesRequestTypePublic, nil
	case "private":
		return DeleteLoadBalancerDatabasesRequestTypePrivate, nil
	}
	var t DeleteLoadBalancerDatabasesRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeleteLoadBalancerDatabasesRequestType) Ptr() *DeleteLoadBalancerDatabasesRequestType {
	return &d
}

var (
	listDatabasesResponseFieldTotal = big.NewInt(1 << 0)
	listDatabasesResponseFieldData  = big.NewInt(1 << 1)
)

type ListDatabasesResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64                     `json:"total" url:"total"`
	Data  []*ClusterDetailResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListDatabasesResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListDatabasesResponse) GetData() []*ClusterDetailResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListDatabasesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListDatabasesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDatabasesResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listDatabasesResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDatabasesResponse) SetData(data []*ClusterDetailResponseDto) {
	l.Data = data
	l.require(listDatabasesResponseFieldData)
}

func (l *ListDatabasesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListDatabasesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListDatabasesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListDatabasesResponse) MarshalJSON() ([]byte, error) {
	type embed ListDatabasesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListDatabasesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ModifyLoadBalancerDatabasesRequestType string

const (
	ModifyLoadBalancerDatabasesRequestTypePublic  ModifyLoadBalancerDatabasesRequestType = "public"
	ModifyLoadBalancerDatabasesRequestTypePrivate ModifyLoadBalancerDatabasesRequestType = "private"
)

func NewModifyLoadBalancerDatabasesRequestTypeFromString(s string) (ModifyLoadBalancerDatabasesRequestType, error) {
	switch s {
	case "public":
		return ModifyLoadBalancerDatabasesRequestTypePublic, nil
	case "private":
		return ModifyLoadBalancerDatabasesRequestTypePrivate, nil
	}
	var t ModifyLoadBalancerDatabasesRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m ModifyLoadBalancerDatabasesRequestType) Ptr() *ModifyLoadBalancerDatabasesRequestType {
	return &m
}
