// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/American-Cloud/americancloud-sdk-go/internal"
	big "math/big"
)

var (
	getByLabelImagesRequestFieldLabel = big.NewInt(1 << 0)
)

type GetByLabelImagesRequest struct {
	// Label of the image to get
	Label string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetByLabelImagesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetByLabelImagesRequest) SetLabel(label string) {
	g.Label = label
	g.require(getByLabelImagesRequestFieldLabel)
}

var (
	getImagesRequestFieldID = big.NewInt(1 << 0)
)

type GetImagesRequest struct {
	// ID of the image to get
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetImagesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetImagesRequest) SetID(id string) {
	g.ID = id
	g.require(getImagesRequestFieldID)
}

var (
	listImagesRequestFieldOs       = big.NewInt(1 << 0)
	listImagesRequestFieldVersion  = big.NewInt(1 << 1)
	listImagesRequestFieldPage     = big.NewInt(1 << 2)
	listImagesRequestFieldPageSize = big.NewInt(1 << 3)
)

type ListImagesRequest struct {
	// Filter images by operating system
	Os *string `json:"-" url:"os,omitempty"`
	// Filter images by OS version (used together with os)
	Version *string `json:"-" url:"version,omitempty"`
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListImagesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetOs sets the Os field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListImagesRequest) SetOs(os *string) {
	l.Os = os
	l.require(listImagesRequestFieldOs)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListImagesRequest) SetVersion(version *string) {
	l.Version = version
	l.require(listImagesRequestFieldVersion)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListImagesRequest) SetPage(page *int) {
	l.Page = page
	l.require(listImagesRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListImagesRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listImagesRequestFieldPageSize)
}

var (
	imageDtoFieldID          = big.NewInt(1 << 0)
	imageDtoFieldLabel       = big.NewInt(1 << 1)
	imageDtoFieldDescription = big.NewInt(1 << 2)
	imageDtoFieldOs          = big.NewInt(1 << 3)
	imageDtoFieldVersion     = big.NewInt(1 << 4)
)

type ImageDto struct {
	// Image ID
	ID string `json:"id" url:"id"`
	// Image label (used as a unique identifier)
	Label string `json:"label" url:"label"`
	// Human-readable display name for the image
	Description string `json:"description" url:"description"`
	// Operating system type
	Os string `json:"os" url:"os"`
	// Operating system version
	Version string `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *ImageDto) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *ImageDto) GetLabel() string {
	if i == nil {
		return ""
	}
	return i.Label
}

func (i *ImageDto) GetDescription() string {
	if i == nil {
		return ""
	}
	return i.Description
}

func (i *ImageDto) GetOs() string {
	if i == nil {
		return ""
	}
	return i.Os
}

func (i *ImageDto) GetVersion() string {
	if i == nil {
		return ""
	}
	return i.Version
}

func (i *ImageDto) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *ImageDto) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImageDto) SetID(id string) {
	i.ID = id
	i.require(imageDtoFieldID)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImageDto) SetLabel(label string) {
	i.Label = label
	i.require(imageDtoFieldLabel)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImageDto) SetDescription(description string) {
	i.Description = description
	i.require(imageDtoFieldDescription)
}

// SetOs sets the Os field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImageDto) SetOs(os string) {
	i.Os = os
	i.require(imageDtoFieldOs)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImageDto) SetVersion(version string) {
	i.Version = version
	i.require(imageDtoFieldVersion)
}

func (i *ImageDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ImageDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImageDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImageDto) MarshalJSON() ([]byte, error) {
	type embed ImageDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *ImageDto) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	listImagesResponseFieldTotal = big.NewInt(1 << 0)
	listImagesResponseFieldData  = big.NewInt(1 << 1)
)

type ListImagesResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64     `json:"total" url:"total"`
	Data  []*ImageDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListImagesResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListImagesResponse) GetData() []*ImageDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListImagesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListImagesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListImagesResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listImagesResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListImagesResponse) SetData(data []*ImageDto) {
	l.Data = data
	l.require(listImagesResponseFieldData)
}

func (l *ListImagesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListImagesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListImagesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListImagesResponse) MarshalJSON() ([]byte, error) {
	type embed ListImagesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListImagesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
