// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/American-Cloud/americancloud-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	createNetworkACLListDtoFieldName        = big.NewInt(1 << 0)
	createNetworkACLListDtoFieldDescription = big.NewInt(1 << 1)
	createNetworkACLListDtoFieldVpcID       = big.NewInt(1 << 2)
)

type CreateNetworkACLListDto struct {
	// Human-readable name for the ACL list.
	Name string `json:"name" url:"-"`
	// Free-form description of the ACL list.
	Description *string `json:"description,omitempty" url:"-"`
	// Identifier of the parent VPC the ACL list belongs to.
	VpcID string `json:"vpcId" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateNetworkACLListDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLListDto) SetName(name string) {
	c.Name = name
	c.require(createNetworkACLListDtoFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLListDto) SetDescription(description *string) {
	c.Description = description
	c.require(createNetworkACLListDtoFieldDescription)
}

// SetVpcID sets the VpcID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLListDto) SetVpcID(vpcID string) {
	c.VpcID = vpcID
	c.require(createNetworkACLListDtoFieldVpcID)
}

func (c *CreateNetworkACLListDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNetworkACLListDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateNetworkACLListDto(body)
	return nil
}

func (c *CreateNetworkACLListDto) MarshalJSON() ([]byte, error) {
	type embed CreateNetworkACLListDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createNetworkACLRuleDtoFieldListID      = big.NewInt(1 << 0)
	createNetworkACLRuleDtoFieldCidrList    = big.NewInt(1 << 1)
	createNetworkACLRuleDtoFieldProtocol    = big.NewInt(1 << 2)
	createNetworkACLRuleDtoFieldAction      = big.NewInt(1 << 3)
	createNetworkACLRuleDtoFieldTrafficType = big.NewInt(1 << 4)
	createNetworkACLRuleDtoFieldNumber      = big.NewInt(1 << 5)
	createNetworkACLRuleDtoFieldStartPort   = big.NewInt(1 << 6)
	createNetworkACLRuleDtoFieldEndPort     = big.NewInt(1 << 7)
	createNetworkACLRuleDtoFieldIcmpType    = big.NewInt(1 << 8)
	createNetworkACLRuleDtoFieldIcmpCode    = big.NewInt(1 << 9)
)

type CreateNetworkACLRuleDto struct {
	// ID of the Network ACL List
	ListID string `json:"-" url:"-"`
	// Remote CIDR — source CIDR for `Ingress` rules, destination CIDR for `Egress` rules.
	CidrList string `json:"cidrList" url:"-"`
	// Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`.
	Protocol string `json:"protocol" url:"-"`
	// Whether to allow or deny matching traffic.
	Action string `json:"action" url:"-"`
	// Direction of traffic the rule applies to.
	TrafficType string `json:"trafficType" url:"-"`
	// Rule number (1-1000). Unique within the ACL list and determines evaluation order.
	Number *string `json:"number,omitempty" url:"-"`
	// Start of the port range. Used for `TCP` and `UDP` protocols.
	StartPort *int `json:"startPort,omitempty" url:"-"`
	// End of the port range. Used for `TCP` and `UDP` protocols.
	EndPort *int `json:"endPort,omitempty" url:"-"`
	// ICMP message type. Used for the `ICMP` protocol.
	IcmpType *string `json:"icmpType,omitempty" url:"-"`
	// ICMP message code. Used for the `ICMP` protocol.
	IcmpCode *string `json:"icmpCode,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateNetworkACLRuleDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetListID sets the ListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetListID(listID string) {
	c.ListID = listID
	c.require(createNetworkACLRuleDtoFieldListID)
}

// SetCidrList sets the CidrList field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetCidrList(cidrList string) {
	c.CidrList = cidrList
	c.require(createNetworkACLRuleDtoFieldCidrList)
}

// SetProtocol sets the Protocol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetProtocol(protocol string) {
	c.Protocol = protocol
	c.require(createNetworkACLRuleDtoFieldProtocol)
}

// SetAction sets the Action field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetAction(action string) {
	c.Action = action
	c.require(createNetworkACLRuleDtoFieldAction)
}

// SetTrafficType sets the TrafficType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetTrafficType(trafficType string) {
	c.TrafficType = trafficType
	c.require(createNetworkACLRuleDtoFieldTrafficType)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetNumber(number *string) {
	c.Number = number
	c.require(createNetworkACLRuleDtoFieldNumber)
}

// SetStartPort sets the StartPort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetStartPort(startPort *int) {
	c.StartPort = startPort
	c.require(createNetworkACLRuleDtoFieldStartPort)
}

// SetEndPort sets the EndPort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetEndPort(endPort *int) {
	c.EndPort = endPort
	c.require(createNetworkACLRuleDtoFieldEndPort)
}

// SetIcmpType sets the IcmpType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetIcmpType(icmpType *string) {
	c.IcmpType = icmpType
	c.require(createNetworkACLRuleDtoFieldIcmpType)
}

// SetIcmpCode sets the IcmpCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNetworkACLRuleDto) SetIcmpCode(icmpCode *string) {
	c.IcmpCode = icmpCode
	c.require(createNetworkACLRuleDtoFieldIcmpCode)
}

func (c *CreateNetworkACLRuleDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNetworkACLRuleDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateNetworkACLRuleDto(body)
	return nil
}

func (c *CreateNetworkACLRuleDto) MarshalJSON() ([]byte, error) {
	type embed CreateNetworkACLRuleDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteListNetworkACLsRequestFieldID = big.NewInt(1 << 0)
)

type DeleteListNetworkACLsRequest struct {
	// ID of the Network ACL List to delete
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteListNetworkACLsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteListNetworkACLsRequest) SetID(id string) {
	d.ID = id
	d.require(deleteListNetworkACLsRequestFieldID)
}

var (
	deleteRuleNetworkACLsRequestFieldID = big.NewInt(1 << 0)
)

type DeleteRuleNetworkACLsRequest struct {
	// ID of the Network ACL Rule to delete
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteRuleNetworkACLsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteRuleNetworkACLsRequest) SetID(id string) {
	d.ID = id
	d.require(deleteRuleNetworkACLsRequestFieldID)
}

var (
	getListNetworkACLsRequestFieldID = big.NewInt(1 << 0)
)

type GetListNetworkACLsRequest struct {
	// ID of the Network ACL List
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetListNetworkACLsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetListNetworkACLsRequest) SetID(id string) {
	g.ID = id
	g.require(getListNetworkACLsRequestFieldID)
}

var (
	getRuleNetworkACLsRequestFieldID = big.NewInt(1 << 0)
)

type GetRuleNetworkACLsRequest struct {
	// ID of the Network ACL Rule
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetRuleNetworkACLsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRuleNetworkACLsRequest) SetID(id string) {
	g.ID = id
	g.require(getRuleNetworkACLsRequestFieldID)
}

var (
	listListsByVpcNetworkACLsRequestFieldVpcID    = big.NewInt(1 << 0)
	listListsByVpcNetworkACLsRequestFieldPage     = big.NewInt(1 << 1)
	listListsByVpcNetworkACLsRequestFieldPageSize = big.NewInt(1 << 2)
)

type ListListsByVpcNetworkACLsRequest struct {
	// ID of the VPC
	VpcID string `json:"-" url:"-"`
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListListsByVpcNetworkACLsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetVpcID sets the VpcID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsByVpcNetworkACLsRequest) SetVpcID(vpcID string) {
	l.VpcID = vpcID
	l.require(listListsByVpcNetworkACLsRequestFieldVpcID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsByVpcNetworkACLsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listListsByVpcNetworkACLsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsByVpcNetworkACLsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listListsByVpcNetworkACLsRequestFieldPageSize)
}

var (
	listListsNetworkACLsRequestFieldPage     = big.NewInt(1 << 0)
	listListsNetworkACLsRequestFieldPageSize = big.NewInt(1 << 1)
)

type ListListsNetworkACLsRequest struct {
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListListsNetworkACLsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsNetworkACLsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listListsNetworkACLsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsNetworkACLsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listListsNetworkACLsRequestFieldPageSize)
}

var (
	listRulesNetworkACLsRequestFieldListID   = big.NewInt(1 << 0)
	listRulesNetworkACLsRequestFieldPage     = big.NewInt(1 << 1)
	listRulesNetworkACLsRequestFieldPageSize = big.NewInt(1 << 2)
)

type ListRulesNetworkACLsRequest struct {
	// ID of the Network ACL List
	ListID string `json:"-" url:"-"`
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListRulesNetworkACLsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetListID sets the ListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesNetworkACLsRequest) SetListID(listID string) {
	l.ListID = listID
	l.require(listRulesNetworkACLsRequestFieldListID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesNetworkACLsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listRulesNetworkACLsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesNetworkACLsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listRulesNetworkACLsRequestFieldPageSize)
}

var (
	replaceNetworkACLListDtoFieldID        = big.NewInt(1 << 0)
	replaceNetworkACLListDtoFieldNetworkID = big.NewInt(1 << 1)
)

type ReplaceNetworkACLListDto struct {
	// ID of the Network ACL List to apply
	ID string `json:"-" url:"-"`
	// Identifier of the network the ACL list should be applied to.
	NetworkID string `json:"networkId" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReplaceNetworkACLListDto) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplaceNetworkACLListDto) SetID(id string) {
	r.ID = id
	r.require(replaceNetworkACLListDtoFieldID)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplaceNetworkACLListDto) SetNetworkID(networkID string) {
	r.NetworkID = networkID
	r.require(replaceNetworkACLListDtoFieldNetworkID)
}

func (r *ReplaceNetworkACLListDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ReplaceNetworkACLListDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ReplaceNetworkACLListDto(body)
	return nil
}

func (r *ReplaceNetworkACLListDto) MarshalJSON() ([]byte, error) {
	type embed ReplaceNetworkACLListDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	networkACLListResponseDtoFieldID          = big.NewInt(1 << 0)
	networkACLListResponseDtoFieldName        = big.NewInt(1 << 1)
	networkACLListResponseDtoFieldDescription = big.NewInt(1 << 2)
	networkACLListResponseDtoFieldVpcID       = big.NewInt(1 << 3)
	networkACLListResponseDtoFieldCreatedAt   = big.NewInt(1 << 4)
)

type NetworkACLListResponseDto struct {
	// Unique identifier for the ACL list.
	ID string `json:"id" url:"id"`
	// Human-readable name for the ACL list.
	Name string `json:"name" url:"name"`
	// Free-form description of the ACL list.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Identifier of the parent VPC the ACL list belongs to. Absent for the account-wide default lists (`default_allow`, `default_deny`).
	VpcID *string `json:"vpcId,omitempty" url:"vpcId,omitempty"`
	// When the ACL list was created.
	CreatedAt *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NetworkACLListResponseDto) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NetworkACLListResponseDto) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NetworkACLListResponseDto) GetDescription() *string {
	if n == nil {
		return nil
	}
	return n.Description
}

func (n *NetworkACLListResponseDto) GetVpcID() *string {
	if n == nil {
		return nil
	}
	return n.VpcID
}

func (n *NetworkACLListResponseDto) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NetworkACLListResponseDto) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NetworkACLListResponseDto) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLListResponseDto) SetID(id string) {
	n.ID = id
	n.require(networkACLListResponseDtoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLListResponseDto) SetName(name string) {
	n.Name = name
	n.require(networkACLListResponseDtoFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLListResponseDto) SetDescription(description *string) {
	n.Description = description
	n.require(networkACLListResponseDtoFieldDescription)
}

// SetVpcID sets the VpcID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLListResponseDto) SetVpcID(vpcID *string) {
	n.VpcID = vpcID
	n.require(networkACLListResponseDtoFieldVpcID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLListResponseDto) SetCreatedAt(createdAt *time.Time) {
	n.CreatedAt = createdAt
	n.require(networkACLListResponseDtoFieldCreatedAt)
}

func (n *NetworkACLListResponseDto) UnmarshalJSON(data []byte) error {
	type embed NetworkACLListResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed: embed(*n),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*n = NetworkACLListResponseDto(unmarshaler.embed)
	n.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NetworkACLListResponseDto) MarshalJSON() ([]byte, error) {
	type embed NetworkACLListResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed:     embed(*n),
		CreatedAt: internal.NewOptionalDateTime(n.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NetworkACLListResponseDto) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	networkACLRuleResponseDtoFieldID          = big.NewInt(1 << 0)
	networkACLRuleResponseDtoFieldACLListID   = big.NewInt(1 << 1)
	networkACLRuleResponseDtoFieldNumber      = big.NewInt(1 << 2)
	networkACLRuleResponseDtoFieldProtocol    = big.NewInt(1 << 3)
	networkACLRuleResponseDtoFieldCidrList    = big.NewInt(1 << 4)
	networkACLRuleResponseDtoFieldAction      = big.NewInt(1 << 5)
	networkACLRuleResponseDtoFieldTrafficType = big.NewInt(1 << 6)
	networkACLRuleResponseDtoFieldStartPort   = big.NewInt(1 << 7)
	networkACLRuleResponseDtoFieldEndPort     = big.NewInt(1 << 8)
	networkACLRuleResponseDtoFieldIcmpType    = big.NewInt(1 << 9)
	networkACLRuleResponseDtoFieldIcmpCode    = big.NewInt(1 << 10)
	networkACLRuleResponseDtoFieldCreatedAt   = big.NewInt(1 << 11)
)

type NetworkACLRuleResponseDto struct {
	// Unique identifier for the ACL rule.
	ID string `json:"id" url:"id"`
	// Identifier of the ACL list the rule belongs to.
	ACLListID string `json:"aclListId" url:"aclListId"`
	// Rule number. Determines evaluation order within the ACL list.
	Number int `json:"number" url:"number"`
	// Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`.
	Protocol string `json:"protocol" url:"protocol"`
	// Remote CIDR — source CIDR for `Ingress` rules, destination CIDR for `Egress` rules.
	CidrList string `json:"cidrList" url:"cidrList"`
	// Whether matching traffic is allowed or denied.
	Action string `json:"action" url:"action"`
	// Direction of traffic the rule applies to.
	TrafficType string `json:"trafficType" url:"trafficType"`
	// Start of the port range. Used for `TCP` and `UDP` protocols.
	StartPort *int `json:"startPort,omitempty" url:"startPort,omitempty"`
	// End of the port range. Used for `TCP` and `UDP` protocols.
	EndPort *int `json:"endPort,omitempty" url:"endPort,omitempty"`
	// ICMP message type. Used for the `ICMP` protocol.
	IcmpType *int `json:"icmpType,omitempty" url:"icmpType,omitempty"`
	// ICMP message code. Used for the `ICMP` protocol.
	IcmpCode *int `json:"icmpCode,omitempty" url:"icmpCode,omitempty"`
	// When the rule was created.
	CreatedAt *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NetworkACLRuleResponseDto) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NetworkACLRuleResponseDto) GetACLListID() string {
	if n == nil {
		return ""
	}
	return n.ACLListID
}

func (n *NetworkACLRuleResponseDto) GetNumber() int {
	if n == nil {
		return 0
	}
	return n.Number
}

func (n *NetworkACLRuleResponseDto) GetProtocol() string {
	if n == nil {
		return ""
	}
	return n.Protocol
}

func (n *NetworkACLRuleResponseDto) GetCidrList() string {
	if n == nil {
		return ""
	}
	return n.CidrList
}

func (n *NetworkACLRuleResponseDto) GetAction() string {
	if n == nil {
		return ""
	}
	return n.Action
}

func (n *NetworkACLRuleResponseDto) GetTrafficType() string {
	if n == nil {
		return ""
	}
	return n.TrafficType
}

func (n *NetworkACLRuleResponseDto) GetStartPort() *int {
	if n == nil {
		return nil
	}
	return n.StartPort
}

func (n *NetworkACLRuleResponseDto) GetEndPort() *int {
	if n == nil {
		return nil
	}
	return n.EndPort
}

func (n *NetworkACLRuleResponseDto) GetIcmpType() *int {
	if n == nil {
		return nil
	}
	return n.IcmpType
}

func (n *NetworkACLRuleResponseDto) GetIcmpCode() *int {
	if n == nil {
		return nil
	}
	return n.IcmpCode
}

func (n *NetworkACLRuleResponseDto) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NetworkACLRuleResponseDto) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NetworkACLRuleResponseDto) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetID(id string) {
	n.ID = id
	n.require(networkACLRuleResponseDtoFieldID)
}

// SetACLListID sets the ACLListID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetACLListID(aclListID string) {
	n.ACLListID = aclListID
	n.require(networkACLRuleResponseDtoFieldACLListID)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetNumber(number int) {
	n.Number = number
	n.require(networkACLRuleResponseDtoFieldNumber)
}

// SetProtocol sets the Protocol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetProtocol(protocol string) {
	n.Protocol = protocol
	n.require(networkACLRuleResponseDtoFieldProtocol)
}

// SetCidrList sets the CidrList field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetCidrList(cidrList string) {
	n.CidrList = cidrList
	n.require(networkACLRuleResponseDtoFieldCidrList)
}

// SetAction sets the Action field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetAction(action string) {
	n.Action = action
	n.require(networkACLRuleResponseDtoFieldAction)
}

// SetTrafficType sets the TrafficType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetTrafficType(trafficType string) {
	n.TrafficType = trafficType
	n.require(networkACLRuleResponseDtoFieldTrafficType)
}

// SetStartPort sets the StartPort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetStartPort(startPort *int) {
	n.StartPort = startPort
	n.require(networkACLRuleResponseDtoFieldStartPort)
}

// SetEndPort sets the EndPort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetEndPort(endPort *int) {
	n.EndPort = endPort
	n.require(networkACLRuleResponseDtoFieldEndPort)
}

// SetIcmpType sets the IcmpType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetIcmpType(icmpType *int) {
	n.IcmpType = icmpType
	n.require(networkACLRuleResponseDtoFieldIcmpType)
}

// SetIcmpCode sets the IcmpCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetIcmpCode(icmpCode *int) {
	n.IcmpCode = icmpCode
	n.require(networkACLRuleResponseDtoFieldIcmpCode)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLRuleResponseDto) SetCreatedAt(createdAt *time.Time) {
	n.CreatedAt = createdAt
	n.require(networkACLRuleResponseDtoFieldCreatedAt)
}

func (n *NetworkACLRuleResponseDto) UnmarshalJSON(data []byte) error {
	type embed NetworkACLRuleResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed: embed(*n),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*n = NetworkACLRuleResponseDto(unmarshaler.embed)
	n.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NetworkACLRuleResponseDto) MarshalJSON() ([]byte, error) {
	type embed NetworkACLRuleResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed:     embed(*n),
		CreatedAt: internal.NewOptionalDateTime(n.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NetworkACLRuleResponseDto) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	listListsByVpcNetworkACLsResponseFieldTotal = big.NewInt(1 << 0)
	listListsByVpcNetworkACLsResponseFieldData  = big.NewInt(1 << 1)
)

type ListListsByVpcNetworkACLsResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64                      `json:"total" url:"total"`
	Data  []*NetworkACLListResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListListsByVpcNetworkACLsResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListListsByVpcNetworkACLsResponse) GetData() []*NetworkACLListResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListListsByVpcNetworkACLsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListListsByVpcNetworkACLsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsByVpcNetworkACLsResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listListsByVpcNetworkACLsResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsByVpcNetworkACLsResponse) SetData(data []*NetworkACLListResponseDto) {
	l.Data = data
	l.require(listListsByVpcNetworkACLsResponseFieldData)
}

func (l *ListListsByVpcNetworkACLsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListListsByVpcNetworkACLsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListListsByVpcNetworkACLsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListListsByVpcNetworkACLsResponse) MarshalJSON() ([]byte, error) {
	type embed ListListsByVpcNetworkACLsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListListsByVpcNetworkACLsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listListsNetworkACLsResponseFieldTotal = big.NewInt(1 << 0)
	listListsNetworkACLsResponseFieldData  = big.NewInt(1 << 1)
)

type ListListsNetworkACLsResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64                      `json:"total" url:"total"`
	Data  []*NetworkACLListResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListListsNetworkACLsResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListListsNetworkACLsResponse) GetData() []*NetworkACLListResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListListsNetworkACLsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListListsNetworkACLsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsNetworkACLsResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listListsNetworkACLsResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListListsNetworkACLsResponse) SetData(data []*NetworkACLListResponseDto) {
	l.Data = data
	l.require(listListsNetworkACLsResponseFieldData)
}

func (l *ListListsNetworkACLsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListListsNetworkACLsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListListsNetworkACLsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListListsNetworkACLsResponse) MarshalJSON() ([]byte, error) {
	type embed ListListsNetworkACLsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListListsNetworkACLsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listRulesNetworkACLsResponseFieldTotal = big.NewInt(1 << 0)
	listRulesNetworkACLsResponseFieldData  = big.NewInt(1 << 1)
)

type ListRulesNetworkACLsResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64                      `json:"total" url:"total"`
	Data  []*NetworkACLRuleResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListRulesNetworkACLsResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListRulesNetworkACLsResponse) GetData() []*NetworkACLRuleResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListRulesNetworkACLsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListRulesNetworkACLsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesNetworkACLsResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listRulesNetworkACLsResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesNetworkACLsResponse) SetData(data []*NetworkACLRuleResponseDto) {
	l.Data = data
	l.require(listRulesNetworkACLsResponseFieldData)
}

func (l *ListRulesNetworkACLsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListRulesNetworkACLsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListRulesNetworkACLsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListRulesNetworkACLsResponse) MarshalJSON() ([]byte, error) {
	type embed ListRulesNetworkACLsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListRulesNetworkACLsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
