// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersCreatePortForwardingRuleDto(t *testing.T) {
	t.Run("SetIpId", func(t *testing.T) {
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueIpId string
		obj.SetIpId(fernTestValueIpId)
		assert.Equal(t, fernTestValueIpId, obj.IpId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrivatePort", func(t *testing.T) {
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValuePrivatePort string
		obj.SetPrivatePort(fernTestValuePrivatePort)
		assert.Equal(t, fernTestValuePrivatePort, obj.PrivatePort)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPublicPort", func(t *testing.T) {
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValuePublicPort string
		obj.SetPublicPort(fernTestValuePublicPort)
		assert.Equal(t, fernTestValuePublicPort, obj.PublicPort)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProtocol", func(t *testing.T) {
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueProtocol CreatePortForwardingRuleDtoProtocol
		obj.SetProtocol(fernTestValueProtocol)
		assert.Equal(t, fernTestValueProtocol, obj.Protocol)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVmId", func(t *testing.T) {
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueVmId string
		obj.SetVmId(fernTestValueVmId)
		assert.Equal(t, fernTestValueVmId, obj.VmId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOpenFirewall", func(t *testing.T) {
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueOpenFirewall *string
		obj.SetOpenFirewall(fernTestValueOpenFirewall)
		assert.Equal(t, fernTestValueOpenFirewall, obj.OpenFirewall)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreatePortForwardingRuleDto(t *testing.T) {
	t.Run("SetIpId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueIpId string

		// Act
		obj.SetIpId(fernTestValueIpId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrivatePort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValuePrivatePort string

		// Act
		obj.SetPrivatePort(fernTestValuePrivatePort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPublicPort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValuePublicPort string

		// Act
		obj.SetPublicPort(fernTestValuePublicPort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProtocol_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueProtocol CreatePortForwardingRuleDtoProtocol

		// Act
		obj.SetProtocol(fernTestValueProtocol)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVmId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueVmId string

		// Act
		obj.SetVmId(fernTestValueVmId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOpenFirewall_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortForwardingRuleDto{}
		var fernTestValueOpenFirewall *string

		// Act
		obj.SetOpenFirewall(fernTestValueOpenFirewall)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeletePortForwardingRequest(t *testing.T) {
	t.Run("SetRuleID", func(t *testing.T) {
		obj := &DeletePortForwardingRequest{}
		var fernTestValueRuleID string
		obj.SetRuleID(fernTestValueRuleID)
		assert.Equal(t, fernTestValueRuleID, obj.RuleID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeletePortForwardingRequest(t *testing.T) {
	t.Run("SetRuleID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeletePortForwardingRequest{}
		var fernTestValueRuleID string

		// Act
		obj.SetRuleID(fernTestValueRuleID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListPortForwardingRequest(t *testing.T) {
	t.Run("SetIpId", func(t *testing.T) {
		obj := &ListPortForwardingRequest{}
		var fernTestValueIpId string
		obj.SetIpId(fernTestValueIpId)
		assert.Equal(t, fernTestValueIpId, obj.IpId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ListPortForwardingRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageSize", func(t *testing.T) {
		obj := &ListPortForwardingRequest{}
		var fernTestValuePageSize *int
		obj.SetPageSize(fernTestValuePageSize)
		assert.Equal(t, fernTestValuePageSize, obj.PageSize)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListPortForwardingRequest(t *testing.T) {
	t.Run("SetIpId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingRequest{}
		var fernTestValueIpId string

		// Act
		obj.SetIpId(fernTestValueIpId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingRequest{}
		var fernTestValuePageSize *int

		// Act
		obj.SetPageSize(fernTestValuePageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPortForwardingRuleResponseDto(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrivatePort", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValuePrivatePort int
		obj.SetPrivatePort(fernTestValuePrivatePort)
		assert.Equal(t, fernTestValuePrivatePort, obj.PrivatePort)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPublicPort", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValuePublicPort int
		obj.SetPublicPort(fernTestValuePublicPort)
		assert.Equal(t, fernTestValuePublicPort, obj.PublicPort)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProtocol", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueProtocol string
		obj.SetProtocol(fernTestValueProtocol)
		assert.Equal(t, fernTestValueProtocol, obj.Protocol)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVmId", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueVmId string
		obj.SetVmId(fernTestValueVmId)
		assert.Equal(t, fernTestValueVmId, obj.VmId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVMName", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueVMName string
		obj.SetVMName(fernTestValueVMName)
		assert.Equal(t, fernTestValueVMName, obj.VMName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIPAddressID", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueIPAddressID string
		obj.SetIPAddressID(fernTestValueIPAddressID)
		assert.Equal(t, fernTestValueIPAddressID, obj.IPAddressID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIPAddress", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueIPAddress string
		obj.SetIPAddress(fernTestValueIPAddress)
		assert.Equal(t, fernTestValueIPAddress, obj.IPAddress)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetState", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueState string
		obj.SetState(fernTestValueState)
		assert.Equal(t, fernTestValueState, obj.State)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueCreatedAt *time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPortForwardingRuleResponseDto(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetPrivatePort", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected int
		obj.PrivatePort = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPrivatePort(), "getter should return the property value")
	})

	t.Run("GetPrivatePort_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPrivatePort() // Should return zero value
	})

	t.Run("GetPublicPort", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected int
		obj.PublicPort = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPublicPort(), "getter should return the property value")
	})

	t.Run("GetPublicPort_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPublicPort() // Should return zero value
	})

	t.Run("GetProtocol", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected string
		obj.Protocol = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProtocol(), "getter should return the property value")
	})

	t.Run("GetProtocol_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProtocol() // Should return zero value
	})

	t.Run("GetVmId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected string
		obj.VmId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVmId(), "getter should return the property value")
	})

	t.Run("GetVmId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVmId() // Should return zero value
	})

	t.Run("GetVMName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected string
		obj.VMName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVMName(), "getter should return the property value")
	})

	t.Run("GetVMName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVMName() // Should return zero value
	})

	t.Run("GetIPAddressID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected string
		obj.IPAddressID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIPAddressID(), "getter should return the property value")
	})

	t.Run("GetIPAddressID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIPAddressID() // Should return zero value
	})

	t.Run("GetIPAddress", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected string
		obj.IPAddress = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIPAddress(), "getter should return the property value")
	})

	t.Run("GetIPAddress_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIPAddress() // Should return zero value
	})

	t.Run("GetState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected string
		obj.State = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetState(), "getter should return the property value")
	})

	t.Run("GetState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetState() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var expected *time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitPortForwardingRuleResponseDto(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrivatePort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValuePrivatePort int

		// Act
		obj.SetPrivatePort(fernTestValuePrivatePort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPublicPort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValuePublicPort int

		// Act
		obj.SetPublicPort(fernTestValuePublicPort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProtocol_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueProtocol string

		// Act
		obj.SetProtocol(fernTestValueProtocol)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVmId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueVmId string

		// Act
		obj.SetVmId(fernTestValueVmId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVMName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueVMName string

		// Act
		obj.SetVMName(fernTestValueVMName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIPAddressID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueIPAddressID string

		// Act
		obj.SetIPAddressID(fernTestValueIPAddressID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIPAddress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueIPAddress string

		// Act
		obj.SetIPAddress(fernTestValueIPAddress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueState string

		// Act
		obj.SetState(fernTestValueState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}
		var fernTestValueCreatedAt *time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListPortForwardingResponse(t *testing.T) {
	t.Run("SetTotal", func(t *testing.T) {
		obj := &ListPortForwardingResponse{}
		var fernTestValueTotal float64
		obj.SetTotal(fernTestValueTotal)
		assert.Equal(t, fernTestValueTotal, obj.Total)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetData", func(t *testing.T) {
		obj := &ListPortForwardingResponse{}
		var fernTestValueData []*PortForwardingRuleResponseDto
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListPortForwardingResponse(t *testing.T) {
	t.Run("GetTotal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingResponse{}
		var expected float64
		obj.Total = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotal(), "getter should return the property value")
	})

	t.Run("GetTotal_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPortForwardingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotal() // Should return zero value
	})

	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingResponse{}
		var expected []*PortForwardingRuleResponseDto
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPortForwardingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

}

func TestSettersMarkExplicitListPortForwardingResponse(t *testing.T) {
	t.Run("SetTotal_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingResponse{}
		var fernTestValueTotal float64

		// Act
		obj.SetTotal(fernTestValueTotal)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingResponse{}
		var fernTestValueData []*PortForwardingRuleResponseDto

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingListPortForwardingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPortForwardingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListPortForwardingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListPortForwardingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListPortForwardingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingPortForwardingRuleResponseDto(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PortForwardingRuleResponseDto{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PortForwardingRuleResponseDto
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PortForwardingRuleResponseDto
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PortForwardingRuleResponseDto
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringListPortForwardingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListPortForwardingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPortForwardingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringPortForwardingRuleResponseDto(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PortForwardingRuleResponseDto{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCreatePortForwardingRuleDtoProtocol(t *testing.T) {
	t.Run("NewFromString_TCP", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePortForwardingRuleDtoProtocolFromString("TCP")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePortForwardingRuleDtoProtocol("TCP"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_UDP", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePortForwardingRuleDtoProtocolFromString("UDP")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePortForwardingRuleDtoProtocol("UDP"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreatePortForwardingRuleDtoProtocolFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreatePortForwardingRuleDtoProtocolFromString("TCP")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesListPortForwardingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListPortForwardingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPortForwardingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesPortForwardingRuleResponseDto(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PortForwardingRuleResponseDto{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PortForwardingRuleResponseDto
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
