// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/American-Cloud/americancloud-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	changeSourceNatIPDtoFieldID        = big.NewInt(1 << 0)
	changeSourceNatIPDtoFieldNetworkID = big.NewInt(1 << 1)
)

type ChangeSourceNatIPDto struct {
	// ID of the public IP address to change
	ID string `json:"-" url:"-"`
	// Identifier of the network whose source NAT IP should be replaced.
	NetworkID string `json:"networkId" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *ChangeSourceNatIPDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChangeSourceNatIPDto) SetID(id string) {
	c.ID = id
	c.require(changeSourceNatIPDtoFieldID)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChangeSourceNatIPDto) SetNetworkID(networkID string) {
	c.NetworkID = networkID
	c.require(changeSourceNatIPDtoFieldNetworkID)
}

func (c *ChangeSourceNatIPDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ChangeSourceNatIPDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = ChangeSourceNatIPDto(body)
	return nil
}

func (c *ChangeSourceNatIPDto) MarshalJSON() ([]byte, error) {
	type embed ChangeSourceNatIPDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	disableStaticNatPublicIpsRequestFieldID = big.NewInt(1 << 0)
)

type DisableStaticNatPublicIpsRequest struct {
	// ID of the public IP address
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DisableStaticNatPublicIpsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DisableStaticNatPublicIpsRequest) SetID(id string) {
	d.ID = id
	d.require(disableStaticNatPublicIpsRequestFieldID)
}

var (
	enableStaticNatDtoFieldID               = big.NewInt(1 << 0)
	enableStaticNatDtoFieldVirtualMachineID = big.NewInt(1 << 1)
)

type EnableStaticNatDto struct {
	// ID of the public IP address
	ID string `json:"-" url:"-"`
	// Identifier of the virtual machine to associate with this public IP.
	VirtualMachineID string `json:"virtualMachineId" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *EnableStaticNatDto) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EnableStaticNatDto) SetID(id string) {
	e.ID = id
	e.require(enableStaticNatDtoFieldID)
}

// SetVirtualMachineID sets the VirtualMachineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EnableStaticNatDto) SetVirtualMachineID(virtualMachineID string) {
	e.VirtualMachineID = virtualMachineID
	e.require(enableStaticNatDtoFieldVirtualMachineID)
}

func (e *EnableStaticNatDto) UnmarshalJSON(data []byte) error {
	type unmarshaler EnableStaticNatDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*e = EnableStaticNatDto(body)
	return nil
}

func (e *EnableStaticNatDto) MarshalJSON() ([]byte, error) {
	type embed EnableStaticNatDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPublicIpsRequestFieldID = big.NewInt(1 << 0)
)

type GetPublicIpsRequest struct {
	// ID of the public IP address
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPublicIpsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPublicIpsRequest) SetID(id string) {
	g.ID = id
	g.require(getPublicIpsRequestFieldID)
}

var (
	listByIsolatedNetworkPublicIpsRequestFieldIsolatedNetworkID = big.NewInt(1 << 0)
	listByIsolatedNetworkPublicIpsRequestFieldPage              = big.NewInt(1 << 1)
	listByIsolatedNetworkPublicIpsRequestFieldPageSize          = big.NewInt(1 << 2)
)

type ListByIsolatedNetworkPublicIpsRequest struct {
	// ID of the isolated network
	IsolatedNetworkID string `json:"-" url:"-"`
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListByIsolatedNetworkPublicIpsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetIsolatedNetworkID sets the IsolatedNetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByIsolatedNetworkPublicIpsRequest) SetIsolatedNetworkID(isolatedNetworkID string) {
	l.IsolatedNetworkID = isolatedNetworkID
	l.require(listByIsolatedNetworkPublicIpsRequestFieldIsolatedNetworkID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByIsolatedNetworkPublicIpsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listByIsolatedNetworkPublicIpsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByIsolatedNetworkPublicIpsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listByIsolatedNetworkPublicIpsRequestFieldPageSize)
}

var (
	listByVpcPublicIpsRequestFieldVpcID    = big.NewInt(1 << 0)
	listByVpcPublicIpsRequestFieldPage     = big.NewInt(1 << 1)
	listByVpcPublicIpsRequestFieldPageSize = big.NewInt(1 << 2)
)

type ListByVpcPublicIpsRequest struct {
	// ID of the VPC
	VpcID string `json:"-" url:"-"`
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListByVpcPublicIpsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetVpcID sets the VpcID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByVpcPublicIpsRequest) SetVpcID(vpcID string) {
	l.VpcID = vpcID
	l.require(listByVpcPublicIpsRequestFieldVpcID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByVpcPublicIpsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listByVpcPublicIpsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByVpcPublicIpsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listByVpcPublicIpsRequestFieldPageSize)
}

var (
	listPublicIpsRequestFieldPage     = big.NewInt(1 << 0)
	listPublicIpsRequestFieldPageSize = big.NewInt(1 << 1)
)

type ListPublicIpsRequest struct {
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPublicIpsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPublicIpsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listPublicIpsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPublicIpsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listPublicIpsRequestFieldPageSize)
}

var (
	releasePublicIpsRequestFieldID = big.NewInt(1 << 0)
)

type ReleasePublicIpsRequest struct {
	// ID of the public IP address to release
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReleasePublicIpsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleasePublicIpsRequest) SetID(id string) {
	r.ID = id
	r.require(releasePublicIpsRequestFieldID)
}

var (
	reservePublicIPDtoFieldNetworkID = big.NewInt(1 << 0)
	reservePublicIPDtoFieldVpcID     = big.NewInt(1 << 1)
	reservePublicIPDtoFieldRegion    = big.NewInt(1 << 2)
)

type ReservePublicIPDto struct {
	// Identifier of the isolated network the public IP should attach to.
	NetworkID *string `json:"networkId,omitempty" url:"-"`
	// Identifier of the VPC the public IP should attach to.
	VpcID *string `json:"vpcId,omitempty" url:"-"`
	// Label of the region where the IP address should be allocated
	Region string `json:"region" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReservePublicIPDto) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservePublicIPDto) SetNetworkID(networkID *string) {
	r.NetworkID = networkID
	r.require(reservePublicIPDtoFieldNetworkID)
}

// SetVpcID sets the VpcID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservePublicIPDto) SetVpcID(vpcID *string) {
	r.VpcID = vpcID
	r.require(reservePublicIPDtoFieldVpcID)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservePublicIPDto) SetRegion(region string) {
	r.Region = region
	r.require(reservePublicIPDtoFieldRegion)
}

func (r *ReservePublicIPDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ReservePublicIPDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ReservePublicIPDto(body)
	return nil
}

func (r *ReservePublicIPDto) MarshalJSON() ([]byte, error) {
	type embed ReservePublicIPDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	publicIPResponseDtoFieldID                    = big.NewInt(1 << 0)
	publicIPResponseDtoFieldIPAddress             = big.NewInt(1 << 1)
	publicIPResponseDtoFieldNetworkID             = big.NewInt(1 << 2)
	publicIPResponseDtoFieldVmId                  = big.NewInt(1 << 3)
	publicIPResponseDtoFieldVMName                = big.NewInt(1 << 4)
	publicIPResponseDtoFieldStatus                = big.NewInt(1 << 5)
	publicIPResponseDtoFieldRegion                = big.NewInt(1 << 6)
	publicIPResponseDtoFieldCreatedAt             = big.NewInt(1 << 7)
	publicIPResponseDtoFieldIsSourceNat           = big.NewInt(1 << 8)
	publicIPResponseDtoFieldIsStaticNat           = big.NewInt(1 << 9)
	publicIPResponseDtoFieldHasFirewallRules      = big.NewInt(1 << 10)
	publicIPResponseDtoFieldVpcID                 = big.NewInt(1 << 11)
	publicIPResponseDtoFieldVpcName               = big.NewInt(1 << 12)
	publicIPResponseDtoFieldAssociatedNetworkID   = big.NewInt(1 << 13)
	publicIPResponseDtoFieldAssociatedNetworkName = big.NewInt(1 << 14)
)

type PublicIPResponseDto struct {
	// Unique identifier for the public IP address.
	ID string `json:"id" url:"id"`
	// The public IPv4 address.
	IPAddress string `json:"ipAddress" url:"ipAddress"`
	// Identifier of the network the IP is associated with.
	NetworkID string `json:"networkId" url:"networkId"`
	// Identifier of the VM the IP is assigned to via static NAT.
	VmId *string `json:"vmId,omitempty" url:"vmId,omitempty"`
	// Name of the VM the IP is assigned to via static NAT.
	VMName *string `json:"vmName,omitempty" url:"vmName,omitempty"`
	// Current lifecycle state of the IP address.
	Status string `json:"status" url:"status"`
	// Region the IP is allocated in.
	Region string `json:"region" url:"region"`
	// When the IP was allocated.
	CreatedAt *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	// Whether this IP is used as the source NAT for its network.
	IsSourceNat bool `json:"isSourceNat" url:"isSourceNat"`
	// Whether this IP is configured as a static NAT.
	IsStaticNat *bool `json:"isStaticNat,omitempty" url:"isStaticNat,omitempty"`
	// Whether any firewall rules currently reference this IP.
	HasFirewallRules *bool `json:"hasFirewallRules,omitempty" url:"hasFirewallRules,omitempty"`
	// Identifier of the VPC the IP is associated with, when applicable.
	VpcID *string `json:"vpcId,omitempty" url:"vpcId,omitempty"`
	// Name of the VPC the IP is associated with, when applicable.
	VpcName *string `json:"vpcName,omitempty" url:"vpcName,omitempty"`
	// Identifier of the network tier the IP is attached to inside the parent VPC.
	AssociatedNetworkID *string `json:"associatedNetworkId,omitempty" url:"associatedNetworkId,omitempty"`
	// Name of the network tier the IP is attached to inside the parent VPC.
	AssociatedNetworkName *string `json:"associatedNetworkName,omitempty" url:"associatedNetworkName,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PublicIPResponseDto) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicIPResponseDto) GetIPAddress() string {
	if p == nil {
		return ""
	}
	return p.IPAddress
}

func (p *PublicIPResponseDto) GetNetworkID() string {
	if p == nil {
		return ""
	}
	return p.NetworkID
}

func (p *PublicIPResponseDto) GetVmId() *string {
	if p == nil {
		return nil
	}
	return p.VmId
}

func (p *PublicIPResponseDto) GetVMName() *string {
	if p == nil {
		return nil
	}
	return p.VMName
}

func (p *PublicIPResponseDto) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PublicIPResponseDto) GetRegion() string {
	if p == nil {
		return ""
	}
	return p.Region
}

func (p *PublicIPResponseDto) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PublicIPResponseDto) GetIsSourceNat() bool {
	if p == nil {
		return false
	}
	return p.IsSourceNat
}

func (p *PublicIPResponseDto) GetIsStaticNat() *bool {
	if p == nil {
		return nil
	}
	return p.IsStaticNat
}

func (p *PublicIPResponseDto) GetHasFirewallRules() *bool {
	if p == nil {
		return nil
	}
	return p.HasFirewallRules
}

func (p *PublicIPResponseDto) GetVpcID() *string {
	if p == nil {
		return nil
	}
	return p.VpcID
}

func (p *PublicIPResponseDto) GetVpcName() *string {
	if p == nil {
		return nil
	}
	return p.VpcName
}

func (p *PublicIPResponseDto) GetAssociatedNetworkID() *string {
	if p == nil {
		return nil
	}
	return p.AssociatedNetworkID
}

func (p *PublicIPResponseDto) GetAssociatedNetworkName() *string {
	if p == nil {
		return nil
	}
	return p.AssociatedNetworkName
}

func (p *PublicIPResponseDto) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PublicIPResponseDto) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetID(id string) {
	p.ID = id
	p.require(publicIPResponseDtoFieldID)
}

// SetIPAddress sets the IPAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetIPAddress(ipAddress string) {
	p.IPAddress = ipAddress
	p.require(publicIPResponseDtoFieldIPAddress)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetNetworkID(networkID string) {
	p.NetworkID = networkID
	p.require(publicIPResponseDtoFieldNetworkID)
}

// SetVmId sets the VmId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetVmId(vmId *string) {
	p.VmId = vmId
	p.require(publicIPResponseDtoFieldVmId)
}

// SetVMName sets the VMName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetVMName(vmName *string) {
	p.VMName = vmName
	p.require(publicIPResponseDtoFieldVMName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetStatus(status string) {
	p.Status = status
	p.require(publicIPResponseDtoFieldStatus)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetRegion(region string) {
	p.Region = region
	p.require(publicIPResponseDtoFieldRegion)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetCreatedAt(createdAt *time.Time) {
	p.CreatedAt = createdAt
	p.require(publicIPResponseDtoFieldCreatedAt)
}

// SetIsSourceNat sets the IsSourceNat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetIsSourceNat(isSourceNat bool) {
	p.IsSourceNat = isSourceNat
	p.require(publicIPResponseDtoFieldIsSourceNat)
}

// SetIsStaticNat sets the IsStaticNat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetIsStaticNat(isStaticNat *bool) {
	p.IsStaticNat = isStaticNat
	p.require(publicIPResponseDtoFieldIsStaticNat)
}

// SetHasFirewallRules sets the HasFirewallRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetHasFirewallRules(hasFirewallRules *bool) {
	p.HasFirewallRules = hasFirewallRules
	p.require(publicIPResponseDtoFieldHasFirewallRules)
}

// SetVpcID sets the VpcID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetVpcID(vpcID *string) {
	p.VpcID = vpcID
	p.require(publicIPResponseDtoFieldVpcID)
}

// SetVpcName sets the VpcName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetVpcName(vpcName *string) {
	p.VpcName = vpcName
	p.require(publicIPResponseDtoFieldVpcName)
}

// SetAssociatedNetworkID sets the AssociatedNetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetAssociatedNetworkID(associatedNetworkID *string) {
	p.AssociatedNetworkID = associatedNetworkID
	p.require(publicIPResponseDtoFieldAssociatedNetworkID)
}

// SetAssociatedNetworkName sets the AssociatedNetworkName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublicIPResponseDto) SetAssociatedNetworkName(associatedNetworkName *string) {
	p.AssociatedNetworkName = associatedNetworkName
	p.require(publicIPResponseDtoFieldAssociatedNetworkName)
}

func (p *PublicIPResponseDto) UnmarshalJSON(data []byte) error {
	type embed PublicIPResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PublicIPResponseDto(unmarshaler.embed)
	p.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PublicIPResponseDto) MarshalJSON() ([]byte, error) {
	type embed PublicIPResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
	}{
		embed:     embed(*p),
		CreatedAt: internal.NewOptionalDateTime(p.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PublicIPResponseDto) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	listByIsolatedNetworkPublicIpsResponseFieldTotal = big.NewInt(1 << 0)
	listByIsolatedNetworkPublicIpsResponseFieldData  = big.NewInt(1 << 1)
)

type ListByIsolatedNetworkPublicIpsResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64                `json:"total" url:"total"`
	Data  []*PublicIPResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListByIsolatedNetworkPublicIpsResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListByIsolatedNetworkPublicIpsResponse) GetData() []*PublicIPResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListByIsolatedNetworkPublicIpsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListByIsolatedNetworkPublicIpsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByIsolatedNetworkPublicIpsResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listByIsolatedNetworkPublicIpsResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByIsolatedNetworkPublicIpsResponse) SetData(data []*PublicIPResponseDto) {
	l.Data = data
	l.require(listByIsolatedNetworkPublicIpsResponseFieldData)
}

func (l *ListByIsolatedNetworkPublicIpsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListByIsolatedNetworkPublicIpsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListByIsolatedNetworkPublicIpsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListByIsolatedNetworkPublicIpsResponse) MarshalJSON() ([]byte, error) {
	type embed ListByIsolatedNetworkPublicIpsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListByIsolatedNetworkPublicIpsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listByVpcPublicIpsResponseFieldTotal = big.NewInt(1 << 0)
	listByVpcPublicIpsResponseFieldData  = big.NewInt(1 << 1)
)

type ListByVpcPublicIpsResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64                `json:"total" url:"total"`
	Data  []*PublicIPResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListByVpcPublicIpsResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListByVpcPublicIpsResponse) GetData() []*PublicIPResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListByVpcPublicIpsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListByVpcPublicIpsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByVpcPublicIpsResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listByVpcPublicIpsResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListByVpcPublicIpsResponse) SetData(data []*PublicIPResponseDto) {
	l.Data = data
	l.require(listByVpcPublicIpsResponseFieldData)
}

func (l *ListByVpcPublicIpsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListByVpcPublicIpsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListByVpcPublicIpsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListByVpcPublicIpsResponse) MarshalJSON() ([]byte, error) {
	type embed ListByVpcPublicIpsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListByVpcPublicIpsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listPublicIpsResponseFieldTotal = big.NewInt(1 << 0)
	listPublicIpsResponseFieldData  = big.NewInt(1 << 1)
)

type ListPublicIpsResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64                `json:"total" url:"total"`
	Data  []*PublicIPResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPublicIpsResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListPublicIpsResponse) GetData() []*PublicIPResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListPublicIpsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListPublicIpsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPublicIpsResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listPublicIpsResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPublicIpsResponse) SetData(data []*PublicIPResponseDto) {
	l.Data = data
	l.require(listPublicIpsResponseFieldData)
}

func (l *ListPublicIpsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPublicIpsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPublicIpsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPublicIpsResponse) MarshalJSON() ([]byte, error) {
	type embed ListPublicIpsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPublicIpsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
