// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/American-Cloud/americancloud-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	createConsoleVmsRequestFieldID = big.NewInt(1 << 0)
)

type CreateConsoleVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateConsoleVmsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateConsoleVmsRequest) SetID(id string) {
	c.ID = id
	c.require(createConsoleVmsRequestFieldID)
}

var (
	deleteVmsRequestFieldID = big.NewInt(1 << 0)
)

type DeleteVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteVmsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteVmsRequest) SetID(id string) {
	d.ID = id
	d.require(deleteVmsRequestFieldID)
}

var (
	getMetricsVmsRequestFieldID           = big.NewInt(1 << 0)
	getMetricsVmsRequestFieldHours        = big.NewInt(1 << 1)
	getMetricsVmsRequestFieldSamplePeriod = big.NewInt(1 << 2)
)

type GetMetricsVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`
	// Number of hours to look back (1-16)
	Hours float64 `json:"-" url:"hours"`
	// Sampling step — return every Nth data point from the raw dataset. Higher values return fewer, more spread-out points. When omitted, up to 150 points are returned.
	SamplePeriod *float64 `json:"-" url:"sample_period,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetMetricsVmsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMetricsVmsRequest) SetID(id string) {
	g.ID = id
	g.require(getMetricsVmsRequestFieldID)
}

// SetHours sets the Hours field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMetricsVmsRequest) SetHours(hours float64) {
	g.Hours = hours
	g.require(getMetricsVmsRequestFieldHours)
}

// SetSamplePeriod sets the SamplePeriod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMetricsVmsRequest) SetSamplePeriod(samplePeriod *float64) {
	g.SamplePeriod = samplePeriod
	g.require(getMetricsVmsRequestFieldSamplePeriod)
}

var (
	getVmsRequestFieldID = big.NewInt(1 << 0)
)

type GetVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetVmsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetVmsRequest) SetID(id string) {
	g.ID = id
	g.require(getVmsRequestFieldID)
}

var (
	listVmsRequestFieldPage     = big.NewInt(1 << 0)
	listVmsRequestFieldPageSize = big.NewInt(1 << 1)
)

type ListVmsRequest struct {
	// Page number, 1-indexed. Defaults to 1 when omitted.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page. Defaults to 100 when omitted; server cap 500.
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListVmsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVmsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listVmsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVmsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listVmsRequestFieldPageSize)
}

var (
	powerVmsRequestFieldID     = big.NewInt(1 << 0)
	powerVmsRequestFieldAction = big.NewInt(1 << 1)
	powerVmsRequestFieldForce  = big.NewInt(1 << 2)
)

type PowerVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`
	// Power action to perform
	Action PowerVmsRequestAction `json:"-" url:"action"`
	// Whether to force the action (applicable for stop and reboot actions)
	Force *bool `json:"-" url:"force,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PowerVmsRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PowerVmsRequest) SetID(id string) {
	p.ID = id
	p.require(powerVmsRequestFieldID)
}

// SetAction sets the Action field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PowerVmsRequest) SetAction(action PowerVmsRequestAction) {
	p.Action = action
	p.require(powerVmsRequestFieldAction)
}

// SetForce sets the Force field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PowerVmsRequest) SetForce(force *bool) {
	p.Force = force
	p.require(powerVmsRequestFieldForce)
}

var (
	reinstallVmsRequestFieldID    = big.NewInt(1 << 0)
	reinstallVmsRequestFieldImage = big.NewInt(1 << 1)
)

type ReinstallVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`
	// Optional image label to reinstall from (uses current template if not provided)
	Image *string `json:"-" url:"image,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReinstallVmsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReinstallVmsRequest) SetID(id string) {
	r.ID = id
	r.require(reinstallVmsRequestFieldID)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReinstallVmsRequest) SetImage(image *string) {
	r.Image = image
	r.require(reinstallVmsRequestFieldImage)
}

var (
	resetPasswordDtoFieldID       = big.NewInt(1 << 0)
	resetPasswordDtoFieldPassword = big.NewInt(1 << 1)
)

type ResetPasswordDto struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`
	// Custom password to set for the VM. If not provided, a random password will be generated.
	Password *string `json:"password,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ResetPasswordDto) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResetPasswordDto) SetID(id string) {
	r.ID = id
	r.require(resetPasswordDtoFieldID)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResetPasswordDto) SetPassword(password *string) {
	r.Password = password
	r.require(resetPasswordDtoFieldPassword)
}

func (r *ResetPasswordDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ResetPasswordDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ResetPasswordDto(body)
	return nil
}

func (r *ResetPasswordDto) MarshalJSON() ([]byte, error) {
	type embed ResetPasswordDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	resizeVMDiskDtoFieldID     = big.NewInt(1 << 0)
	resizeVMDiskDtoFieldSizeGb = big.NewInt(1 << 1)
	resizeVMDiskDtoFieldReboot = big.NewInt(1 << 2)
)

type ResizeVMDiskDto struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`
	// The new size of the root disk in GB. Must be larger than the current root disk size.
	SizeGb int `json:"sizeGb" url:"-"`
	// Whether to automatically reboot the VM after the resize completes. Only applies when the VM is running. A reboot is required for the OS to recognize the new disk size.
	Reboot *bool `json:"reboot,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ResizeVMDiskDto) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResizeVMDiskDto) SetID(id string) {
	r.ID = id
	r.require(resizeVMDiskDtoFieldID)
}

// SetSizeGb sets the SizeGb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResizeVMDiskDto) SetSizeGb(sizeGb int) {
	r.SizeGb = sizeGb
	r.require(resizeVMDiskDtoFieldSizeGb)
}

// SetReboot sets the Reboot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResizeVMDiskDto) SetReboot(reboot *bool) {
	r.Reboot = reboot
	r.require(resizeVMDiskDtoFieldReboot)
}

func (r *ResizeVMDiskDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ResizeVMDiskDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ResizeVMDiskDto(body)
	return nil
}

func (r *ResizeVMDiskDto) MarshalJSON() ([]byte, error) {
	type embed ResizeVMDiskDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	scaleVmsRequestFieldID       = big.NewInt(1 << 0)
	scaleVmsRequestFieldCPU      = big.NewInt(1 << 1)
	scaleVmsRequestFieldMemoryMb = big.NewInt(1 << 2)
)

type ScaleVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`
	// Number of virtual CPUs (optional, but at least one of CPU or memory must be provided)
	CPU *float64 `json:"-" url:"cpu,omitempty"`
	// Memory in MB (optional, but at least one of CPU or memory must be provided)
	MemoryMb *float64 `json:"-" url:"memoryMb,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ScaleVmsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScaleVmsRequest) SetID(id string) {
	s.ID = id
	s.require(scaleVmsRequestFieldID)
}

// SetCPU sets the CPU field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScaleVmsRequest) SetCPU(cpu *float64) {
	s.CPU = cpu
	s.require(scaleVmsRequestFieldCPU)
}

// SetMemoryMb sets the MemoryMb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScaleVmsRequest) SetMemoryMb(memoryMb *float64) {
	s.MemoryMb = memoryMb
	s.require(scaleVmsRequestFieldMemoryMb)
}

var (
	createVMDtoFieldName               = big.NewInt(1 << 0)
	createVMDtoFieldRegion             = big.NewInt(1 << 1)
	createVMDtoFieldVMPackage          = big.NewInt(1 << 2)
	createVMDtoFieldVMSpecs            = big.NewInt(1 << 3)
	createVMDtoFieldImage              = big.NewInt(1 << 4)
	createVMDtoFieldNetwork            = big.NewInt(1 << 5)
	createVMDtoFieldSubscriptionPeriod = big.NewInt(1 << 6)
	createVMDtoFieldTags               = big.NewInt(1 << 7)
	createVMDtoFieldKeypairs           = big.NewInt(1 << 8)
	createVMDtoFieldUserdata           = big.NewInt(1 << 9)
	createVMDtoFieldNetworkAccess      = big.NewInt(1 << 10)
)

type CreateVMDto struct {
	// VM name
	Name string `json:"name" url:"name"`
	// Region label
	Region string `json:"region" url:"region"`
	// VM package label
	VMPackage string `json:"vmPackage" url:"vmPackage"`
	// VM specifications
	VMSpecs *VMSpecsDto `json:"vmSpecs" url:"vmSpecs"`
	// Image label to use for the VM
	Image string `json:"image" url:"image"`
	// UUID of pre-existing customer network
	Network string `json:"network" url:"network"`
	// Subscription period
	SubscriptionPeriod CreateVMDtoSubscriptionPeriod `json:"subscriptionPeriod" url:"subscriptionPeriod"`
	// List of tags to add to the VM
	Tags []string `json:"tags,omitempty" url:"tags,omitempty"`
	// Names of SSH key pairs to use (optional)
	Keypairs []string `json:"keypairs,omitempty" url:"keypairs,omitempty"`
	// Base64-encoded cloud-init userdata script (optional)
	Userdata *string `json:"userdata,omitempty" url:"userdata,omitempty"`
	// Optional network access configuration applied after the VM is created. Only honored when no `network` is provided (i.e. an isolated network is auto-created). Creates an egress allow-all rule (if requested) and adds port forwarding + firewall rules for the requested inbound ports against the network's public IP.
	NetworkAccess *NetworkAccessDto `json:"networkAccess,omitempty" url:"networkAccess,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateVMDto) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateVMDto) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *CreateVMDto) GetVMPackage() string {
	if c == nil {
		return ""
	}
	return c.VMPackage
}

func (c *CreateVMDto) GetVMSpecs() *VMSpecsDto {
	if c == nil {
		return nil
	}
	return c.VMSpecs
}

func (c *CreateVMDto) GetImage() string {
	if c == nil {
		return ""
	}
	return c.Image
}

func (c *CreateVMDto) GetNetwork() string {
	if c == nil {
		return ""
	}
	return c.Network
}

func (c *CreateVMDto) GetSubscriptionPeriod() CreateVMDtoSubscriptionPeriod {
	if c == nil {
		return ""
	}
	return c.SubscriptionPeriod
}

func (c *CreateVMDto) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CreateVMDto) GetKeypairs() []string {
	if c == nil {
		return nil
	}
	return c.Keypairs
}

func (c *CreateVMDto) GetUserdata() *string {
	if c == nil {
		return nil
	}
	return c.Userdata
}

func (c *CreateVMDto) GetNetworkAccess() *NetworkAccessDto {
	if c == nil {
		return nil
	}
	return c.NetworkAccess
}

func (c *CreateVMDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateVMDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetName(name string) {
	c.Name = name
	c.require(createVMDtoFieldName)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetRegion(region string) {
	c.Region = region
	c.require(createVMDtoFieldRegion)
}

// SetVMPackage sets the VMPackage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetVMPackage(vmPackage string) {
	c.VMPackage = vmPackage
	c.require(createVMDtoFieldVMPackage)
}

// SetVMSpecs sets the VMSpecs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetVMSpecs(vmSpecs *VMSpecsDto) {
	c.VMSpecs = vmSpecs
	c.require(createVMDtoFieldVMSpecs)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetImage(image string) {
	c.Image = image
	c.require(createVMDtoFieldImage)
}

// SetNetwork sets the Network field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetNetwork(network string) {
	c.Network = network
	c.require(createVMDtoFieldNetwork)
}

// SetSubscriptionPeriod sets the SubscriptionPeriod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetSubscriptionPeriod(subscriptionPeriod CreateVMDtoSubscriptionPeriod) {
	c.SubscriptionPeriod = subscriptionPeriod
	c.require(createVMDtoFieldSubscriptionPeriod)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetTags(tags []string) {
	c.Tags = tags
	c.require(createVMDtoFieldTags)
}

// SetKeypairs sets the Keypairs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetKeypairs(keypairs []string) {
	c.Keypairs = keypairs
	c.require(createVMDtoFieldKeypairs)
}

// SetUserdata sets the Userdata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetUserdata(userdata *string) {
	c.Userdata = userdata
	c.require(createVMDtoFieldUserdata)
}

// SetNetworkAccess sets the NetworkAccess field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMDto) SetNetworkAccess(networkAccess *NetworkAccessDto) {
	c.NetworkAccess = networkAccess
	c.require(createVMDtoFieldNetworkAccess)
}

func (c *CreateVMDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateVMDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateVMDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateVMDto) MarshalJSON() ([]byte, error) {
	type embed CreateVMDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateVMDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Subscription period
type CreateVMDtoSubscriptionPeriod string

const (
	CreateVMDtoSubscriptionPeriodHourly  CreateVMDtoSubscriptionPeriod = "hourly"
	CreateVMDtoSubscriptionPeriodMonthly CreateVMDtoSubscriptionPeriod = "monthly"
)

func NewCreateVMDtoSubscriptionPeriodFromString(s string) (CreateVMDtoSubscriptionPeriod, error) {
	switch s {
	case "hourly":
		return CreateVMDtoSubscriptionPeriodHourly, nil
	case "monthly":
		return CreateVMDtoSubscriptionPeriodMonthly, nil
	}
	var t CreateVMDtoSubscriptionPeriod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateVMDtoSubscriptionPeriod) Ptr() *CreateVMDtoSubscriptionPeriod {
	return &c
}

var (
	createVMResponseDtoFieldID                 = big.NewInt(1 << 0)
	createVMResponseDtoFieldName               = big.NewInt(1 << 1)
	createVMResponseDtoFieldStatus             = big.NewInt(1 << 2)
	createVMResponseDtoFieldRegion             = big.NewInt(1 << 3)
	createVMResponseDtoFieldVMPackage          = big.NewInt(1 << 4)
	createVMResponseDtoFieldCPU                = big.NewInt(1 << 5)
	createVMResponseDtoFieldMemoryMb           = big.NewInt(1 << 6)
	createVMResponseDtoFieldRootDiskGb         = big.NewInt(1 << 7)
	createVMResponseDtoFieldTags               = big.NewInt(1 << 8)
	createVMResponseDtoFieldSubscriptionPeriod = big.NewInt(1 << 9)
	createVMResponseDtoFieldImage              = big.NewInt(1 << 10)
	createVMResponseDtoFieldImageDisplayName   = big.NewInt(1 << 11)
	createVMResponseDtoFieldIPAddress          = big.NewInt(1 << 12)
	createVMResponseDtoFieldNetworkName        = big.NewInt(1 << 13)
	createVMResponseDtoFieldNetworkID          = big.NewInt(1 << 14)
	createVMResponseDtoFieldRootVolumeID       = big.NewInt(1 << 15)
	createVMResponseDtoFieldCreatedAt          = big.NewInt(1 << 16)
	createVMResponseDtoFieldVersionStartedAt   = big.NewInt(1 << 17)
	createVMResponseDtoFieldMarketplaceApp     = big.NewInt(1 << 18)
	createVMResponseDtoFieldPasswordMessage    = big.NewInt(1 << 19)
)

type CreateVMResponseDto struct {
	// Unique identifier for this virtual machine.
	ID string `json:"id" url:"id"`
	// Human-readable name for the VM. Shown in dashboards and CLI output.
	Name string `json:"name" url:"name"`
	// Current lifecycle state of the VM.
	Status string `json:"status" url:"status"`
	// Region the VM is provisioned in. References a region label from /v1/compute/regions.
	Region string `json:"region" url:"region"`
	// Package label identifying the CPU/memory/disk preset this VM uses.
	VMPackage *string `json:"vmPackage,omitempty" url:"vmPackage,omitempty"`
	// Number of virtual CPUs allocated to the VM.
	CPU int `json:"cpu" url:"cpu"`
	// Memory allocated to the VM, in megabytes.
	MemoryMb int `json:"memoryMb" url:"memoryMb"`
	// Root disk size, in gigabytes.
	RootDiskGb int `json:"rootDiskGb" url:"rootDiskGb"`
	// Tags assigned to this VM for grouping and filtering.
	Tags []string `json:"tags,omitempty" url:"tags,omitempty"`
	// Billing cadence applied to this VM.
	SubscriptionPeriod string `json:"subscriptionPeriod" url:"subscriptionPeriod"`
	// Image label the VM was provisioned from. References /v1/compute/images.
	Image string `json:"image" url:"image"`
	// Friendly name of the source image.
	ImageDisplayName *string `json:"imageDisplayName,omitempty" url:"imageDisplayName,omitempty"`
	// Primary IP address assigned to the VM on its network.
	IPAddress string `json:"ipAddress" url:"ipAddress"`
	// Name of the network or VPC tier this VM is attached to.
	NetworkName string `json:"networkName" url:"networkName"`
	// Identifier of the network or VPC tier this VM is attached to.
	NetworkID string `json:"networkId" url:"networkId"`
	// Identifier of the VM root volume.
	RootVolumeID string `json:"rootVolumeId" url:"rootVolumeId"`
	// When the VM was first provisioned.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// When the current billing version started (set when the VM is scaled or its disk is resized). Only present if the VM has been modified since creation.
	VersionStartedAt *time.Time `json:"versionStartedAt,omitempty" url:"versionStartedAt,omitempty"`
	// Source marketplace app, when the VM was deployed from one. Absent for OS-only deploys.
	MarketplaceApp *MarketplaceAppDto `json:"marketplaceApp,omitempty" url:"marketplaceApp,omitempty"`
	// Human-readable note explaining how the initial VM password will be delivered.
	PasswordMessage string `json:"passwordMessage" url:"passwordMessage"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateVMResponseDto) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateVMResponseDto) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateVMResponseDto) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateVMResponseDto) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *CreateVMResponseDto) GetVMPackage() *string {
	if c == nil {
		return nil
	}
	return c.VMPackage
}

func (c *CreateVMResponseDto) GetCPU() int {
	if c == nil {
		return 0
	}
	return c.CPU
}

func (c *CreateVMResponseDto) GetMemoryMb() int {
	if c == nil {
		return 0
	}
	return c.MemoryMb
}

func (c *CreateVMResponseDto) GetRootDiskGb() int {
	if c == nil {
		return 0
	}
	return c.RootDiskGb
}

func (c *CreateVMResponseDto) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CreateVMResponseDto) GetSubscriptionPeriod() string {
	if c == nil {
		return ""
	}
	return c.SubscriptionPeriod
}

func (c *CreateVMResponseDto) GetImage() string {
	if c == nil {
		return ""
	}
	return c.Image
}

func (c *CreateVMResponseDto) GetImageDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.ImageDisplayName
}

func (c *CreateVMResponseDto) GetIPAddress() string {
	if c == nil {
		return ""
	}
	return c.IPAddress
}

func (c *CreateVMResponseDto) GetNetworkName() string {
	if c == nil {
		return ""
	}
	return c.NetworkName
}

func (c *CreateVMResponseDto) GetNetworkID() string {
	if c == nil {
		return ""
	}
	return c.NetworkID
}

func (c *CreateVMResponseDto) GetRootVolumeID() string {
	if c == nil {
		return ""
	}
	return c.RootVolumeID
}

func (c *CreateVMResponseDto) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreateVMResponseDto) GetVersionStartedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.VersionStartedAt
}

func (c *CreateVMResponseDto) GetMarketplaceApp() *MarketplaceAppDto {
	if c == nil {
		return nil
	}
	return c.MarketplaceApp
}

func (c *CreateVMResponseDto) GetPasswordMessage() string {
	if c == nil {
		return ""
	}
	return c.PasswordMessage
}

func (c *CreateVMResponseDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateVMResponseDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetID(id string) {
	c.ID = id
	c.require(createVMResponseDtoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetName(name string) {
	c.Name = name
	c.require(createVMResponseDtoFieldName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetStatus(status string) {
	c.Status = status
	c.require(createVMResponseDtoFieldStatus)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetRegion(region string) {
	c.Region = region
	c.require(createVMResponseDtoFieldRegion)
}

// SetVMPackage sets the VMPackage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetVMPackage(vmPackage *string) {
	c.VMPackage = vmPackage
	c.require(createVMResponseDtoFieldVMPackage)
}

// SetCPU sets the CPU field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetCPU(cpu int) {
	c.CPU = cpu
	c.require(createVMResponseDtoFieldCPU)
}

// SetMemoryMb sets the MemoryMb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetMemoryMb(memoryMb int) {
	c.MemoryMb = memoryMb
	c.require(createVMResponseDtoFieldMemoryMb)
}

// SetRootDiskGb sets the RootDiskGb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetRootDiskGb(rootDiskGb int) {
	c.RootDiskGb = rootDiskGb
	c.require(createVMResponseDtoFieldRootDiskGb)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetTags(tags []string) {
	c.Tags = tags
	c.require(createVMResponseDtoFieldTags)
}

// SetSubscriptionPeriod sets the SubscriptionPeriod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetSubscriptionPeriod(subscriptionPeriod string) {
	c.SubscriptionPeriod = subscriptionPeriod
	c.require(createVMResponseDtoFieldSubscriptionPeriod)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetImage(image string) {
	c.Image = image
	c.require(createVMResponseDtoFieldImage)
}

// SetImageDisplayName sets the ImageDisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetImageDisplayName(imageDisplayName *string) {
	c.ImageDisplayName = imageDisplayName
	c.require(createVMResponseDtoFieldImageDisplayName)
}

// SetIPAddress sets the IPAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetIPAddress(ipAddress string) {
	c.IPAddress = ipAddress
	c.require(createVMResponseDtoFieldIPAddress)
}

// SetNetworkName sets the NetworkName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetNetworkName(networkName string) {
	c.NetworkName = networkName
	c.require(createVMResponseDtoFieldNetworkName)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetNetworkID(networkID string) {
	c.NetworkID = networkID
	c.require(createVMResponseDtoFieldNetworkID)
}

// SetRootVolumeID sets the RootVolumeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetRootVolumeID(rootVolumeID string) {
	c.RootVolumeID = rootVolumeID
	c.require(createVMResponseDtoFieldRootVolumeID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(createVMResponseDtoFieldCreatedAt)
}

// SetVersionStartedAt sets the VersionStartedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetVersionStartedAt(versionStartedAt *time.Time) {
	c.VersionStartedAt = versionStartedAt
	c.require(createVMResponseDtoFieldVersionStartedAt)
}

// SetMarketplaceApp sets the MarketplaceApp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetMarketplaceApp(marketplaceApp *MarketplaceAppDto) {
	c.MarketplaceApp = marketplaceApp
	c.require(createVMResponseDtoFieldMarketplaceApp)
}

// SetPasswordMessage sets the PasswordMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVMResponseDto) SetPasswordMessage(passwordMessage string) {
	c.PasswordMessage = passwordMessage
	c.require(createVMResponseDtoFieldPasswordMessage)
}

func (c *CreateVMResponseDto) UnmarshalJSON(data []byte) error {
	type embed CreateVMResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt        *internal.DateTime `json:"createdAt"`
		VersionStartedAt *internal.DateTime `json:"versionStartedAt,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateVMResponseDto(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.VersionStartedAt = unmarshaler.VersionStartedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateVMResponseDto) MarshalJSON() ([]byte, error) {
	type embed CreateVMResponseDto
	var marshaler = struct {
		embed
		CreatedAt        *internal.DateTime `json:"createdAt"`
		VersionStartedAt *internal.DateTime `json:"versionStartedAt,omitempty"`
	}{
		embed:            embed(*c),
		CreatedAt:        internal.NewDateTime(c.CreatedAt),
		VersionStartedAt: internal.NewOptionalDateTime(c.VersionStartedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateVMResponseDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	inboundPortDtoFieldPort     = big.NewInt(1 << 0)
	inboundPortDtoFieldProtocol = big.NewInt(1 << 1)
)

type InboundPortDto struct {
	// Port number to open for inbound traffic
	Port     int                    `json:"port" url:"port"`
	Protocol InboundPortDtoProtocol `json:"protocol" url:"protocol"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InboundPortDto) GetPort() int {
	if i == nil {
		return 0
	}
	return i.Port
}

func (i *InboundPortDto) GetProtocol() InboundPortDtoProtocol {
	if i == nil {
		return ""
	}
	return i.Protocol
}

func (i *InboundPortDto) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InboundPortDto) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetPort sets the Port field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InboundPortDto) SetPort(port int) {
	i.Port = port
	i.require(inboundPortDtoFieldPort)
}

// SetProtocol sets the Protocol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InboundPortDto) SetProtocol(protocol InboundPortDtoProtocol) {
	i.Protocol = protocol
	i.require(inboundPortDtoFieldProtocol)
}

func (i *InboundPortDto) UnmarshalJSON(data []byte) error {
	type unmarshaler InboundPortDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InboundPortDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InboundPortDto) MarshalJSON() ([]byte, error) {
	type embed InboundPortDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InboundPortDto) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InboundPortDtoProtocol string

const (
	InboundPortDtoProtocolTCP InboundPortDtoProtocol = "TCP"
	InboundPortDtoProtocolUDP InboundPortDtoProtocol = "UDP"
)

func NewInboundPortDtoProtocolFromString(s string) (InboundPortDtoProtocol, error) {
	switch s {
	case "TCP":
		return InboundPortDtoProtocolTCP, nil
	case "UDP":
		return InboundPortDtoProtocolUDP, nil
	}
	var t InboundPortDtoProtocol
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InboundPortDtoProtocol) Ptr() *InboundPortDtoProtocol {
	return &i
}

var (
	marketplaceAppDtoFieldLabel   = big.NewInt(1 << 0)
	marketplaceAppDtoFieldName    = big.NewInt(1 << 1)
	marketplaceAppDtoFieldDocsURL = big.NewInt(1 << 2)
)

type MarketplaceAppDto struct {
	// Marketplace app slug (URL-safe identifier)
	Label string `json:"label" url:"label"`
	// Marketplace app display name
	Name string `json:"name" url:"name"`
	// Link to the app's docs page. May be null if not configured.
	DocsURL *string `json:"docsUrl,omitempty" url:"docsUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MarketplaceAppDto) GetLabel() string {
	if m == nil {
		return ""
	}
	return m.Label
}

func (m *MarketplaceAppDto) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MarketplaceAppDto) GetDocsURL() *string {
	if m == nil {
		return nil
	}
	return m.DocsURL
}

func (m *MarketplaceAppDto) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MarketplaceAppDto) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarketplaceAppDto) SetLabel(label string) {
	m.Label = label
	m.require(marketplaceAppDtoFieldLabel)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarketplaceAppDto) SetName(name string) {
	m.Name = name
	m.require(marketplaceAppDtoFieldName)
}

// SetDocsURL sets the DocsURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarketplaceAppDto) SetDocsURL(docsURL *string) {
	m.DocsURL = docsURL
	m.require(marketplaceAppDtoFieldDocsURL)
}

func (m *MarketplaceAppDto) UnmarshalJSON(data []byte) error {
	type unmarshaler MarketplaceAppDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MarketplaceAppDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MarketplaceAppDto) MarshalJSON() ([]byte, error) {
	type embed MarketplaceAppDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MarketplaceAppDto) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	networkAccessDtoFieldAllowEgressAll = big.NewInt(1 << 0)
	networkAccessDtoFieldInboundPorts   = big.NewInt(1 << 1)
	networkAccessDtoFieldSourceCidr     = big.NewInt(1 << 2)
)

type NetworkAccessDto struct {
	// Allow all outbound traffic from the VM. New isolated networks deny outbound by default.
	AllowEgressAll bool `json:"allowEgressAll" url:"allowEgressAll"`
	// Inbound ports to open on the network's public IP. Omit or empty for no inbound. When provided, port forwarding and firewall rules are created on the source NAT IP.
	InboundPorts []*InboundPortDto `json:"inboundPorts,omitempty" url:"inboundPorts,omitempty"`
	// Source CIDR(s) allowed to reach the inbound ports. Comma-separated for multiple.
	SourceCidr *string `json:"sourceCidr,omitempty" url:"sourceCidr,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NetworkAccessDto) GetAllowEgressAll() bool {
	if n == nil {
		return false
	}
	return n.AllowEgressAll
}

func (n *NetworkAccessDto) GetInboundPorts() []*InboundPortDto {
	if n == nil {
		return nil
	}
	return n.InboundPorts
}

func (n *NetworkAccessDto) GetSourceCidr() *string {
	if n == nil {
		return nil
	}
	return n.SourceCidr
}

func (n *NetworkAccessDto) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NetworkAccessDto) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetAllowEgressAll sets the AllowEgressAll field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkAccessDto) SetAllowEgressAll(allowEgressAll bool) {
	n.AllowEgressAll = allowEgressAll
	n.require(networkAccessDtoFieldAllowEgressAll)
}

// SetInboundPorts sets the InboundPorts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkAccessDto) SetInboundPorts(inboundPorts []*InboundPortDto) {
	n.InboundPorts = inboundPorts
	n.require(networkAccessDtoFieldInboundPorts)
}

// SetSourceCidr sets the SourceCidr field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkAccessDto) SetSourceCidr(sourceCidr *string) {
	n.SourceCidr = sourceCidr
	n.require(networkAccessDtoFieldSourceCidr)
}

func (n *NetworkAccessDto) UnmarshalJSON(data []byte) error {
	type unmarshaler NetworkAccessDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NetworkAccessDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NetworkAccessDto) MarshalJSON() ([]byte, error) {
	type embed NetworkAccessDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NetworkAccessDto) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	vMConsoleResponseDtoFieldURL = big.NewInt(1 << 0)
)

type VMConsoleResponseDto struct {
	// Signed console URL for accessing the VM. Single-use; request a new one if it expires.
	URL string `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMConsoleResponseDto) GetURL() string {
	if v == nil {
		return ""
	}
	return v.URL
}

func (v *VMConsoleResponseDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMConsoleResponseDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMConsoleResponseDto) SetURL(url string) {
	v.URL = url
	v.require(vMConsoleResponseDtoFieldURL)
}

func (v *VMConsoleResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VMConsoleResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VMConsoleResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMConsoleResponseDto) MarshalJSON() ([]byte, error) {
	type embed VMConsoleResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMConsoleResponseDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vMDiskResizeResponseDtoFieldID              = big.NewInt(1 << 0)
	vMDiskResizeResponseDtoFieldStatus          = big.NewInt(1 << 1)
	vMDiskResizeResponseDtoFieldRebootInitiated = big.NewInt(1 << 2)
	vMDiskResizeResponseDtoFieldMessage         = big.NewInt(1 << 3)
)

type VMDiskResizeResponseDto struct {
	// Virtual machine ID.
	ID string `json:"id" url:"id"`
	// Transitional state during the resize.
	Status string `json:"status" url:"status"`
	// True when the VM was running and `reboot=true`, so the new disk size was applied via a reboot. False otherwise (VM was already stopped, or `reboot=false`, or the reboot step failed — see `message`).
	RebootInitiated bool `json:"rebootInitiated" url:"rebootInitiated"`
	// Present only when the disk resize succeeded but the follow-up reboot failed; surfaces a remediation hint to the caller.
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMDiskResizeResponseDto) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VMDiskResizeResponseDto) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *VMDiskResizeResponseDto) GetRebootInitiated() bool {
	if v == nil {
		return false
	}
	return v.RebootInitiated
}

func (v *VMDiskResizeResponseDto) GetMessage() *string {
	if v == nil {
		return nil
	}
	return v.Message
}

func (v *VMDiskResizeResponseDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMDiskResizeResponseDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMDiskResizeResponseDto) SetID(id string) {
	v.ID = id
	v.require(vMDiskResizeResponseDtoFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMDiskResizeResponseDto) SetStatus(status string) {
	v.Status = status
	v.require(vMDiskResizeResponseDtoFieldStatus)
}

// SetRebootInitiated sets the RebootInitiated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMDiskResizeResponseDto) SetRebootInitiated(rebootInitiated bool) {
	v.RebootInitiated = rebootInitiated
	v.require(vMDiskResizeResponseDtoFieldRebootInitiated)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMDiskResizeResponseDto) SetMessage(message *string) {
	v.Message = message
	v.require(vMDiskResizeResponseDtoFieldMessage)
}

func (v *VMDiskResizeResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VMDiskResizeResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VMDiskResizeResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMDiskResizeResponseDto) MarshalJSON() ([]byte, error) {
	type embed VMDiskResizeResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMDiskResizeResponseDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vMHostnameUpdateResponseDtoFieldID       = big.NewInt(1 << 0)
	vMHostnameUpdateResponseDtoFieldHostname = big.NewInt(1 << 1)
	vMHostnameUpdateResponseDtoFieldStatus   = big.NewInt(1 << 2)
	vMHostnameUpdateResponseDtoFieldMessage  = big.NewInt(1 << 3)
)

type VMHostnameUpdateResponseDto struct {
	// Virtual machine ID.
	ID string `json:"id" url:"id"`
	// The newly-set hostname.
	Hostname string `json:"hostname" url:"hostname"`
	// Status of the hostname update.
	Status string `json:"status" url:"status"`
	// Reminder that the VM must be stopped and started for the change to take effect.
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMHostnameUpdateResponseDto) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VMHostnameUpdateResponseDto) GetHostname() string {
	if v == nil {
		return ""
	}
	return v.Hostname
}

func (v *VMHostnameUpdateResponseDto) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *VMHostnameUpdateResponseDto) GetMessage() *string {
	if v == nil {
		return nil
	}
	return v.Message
}

func (v *VMHostnameUpdateResponseDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMHostnameUpdateResponseDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMHostnameUpdateResponseDto) SetID(id string) {
	v.ID = id
	v.require(vMHostnameUpdateResponseDtoFieldID)
}

// SetHostname sets the Hostname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMHostnameUpdateResponseDto) SetHostname(hostname string) {
	v.Hostname = hostname
	v.require(vMHostnameUpdateResponseDtoFieldHostname)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMHostnameUpdateResponseDto) SetStatus(status string) {
	v.Status = status
	v.require(vMHostnameUpdateResponseDtoFieldStatus)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMHostnameUpdateResponseDto) SetMessage(message *string) {
	v.Message = message
	v.require(vMHostnameUpdateResponseDtoFieldMessage)
}

func (v *VMHostnameUpdateResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VMHostnameUpdateResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VMHostnameUpdateResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMHostnameUpdateResponseDto) MarshalJSON() ([]byte, error) {
	type embed VMHostnameUpdateResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMHostnameUpdateResponseDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vMMetricSampleDtoFieldTimestamp      = big.NewInt(1 << 0)
	vMMetricSampleDtoFieldCPUUsagePct    = big.NewInt(1 << 1)
	vMMetricSampleDtoFieldMemoryUsagePct = big.NewInt(1 << 2)
)

type VMMetricSampleDto struct {
	// Sample timestamp from the underlying compute platform.
	Timestamp time.Time `json:"timestamp" url:"timestamp"`
	// CPU usage as a percentage (0–100), rounded to two decimal places.
	CPUUsagePct float64 `json:"cpuUsagePct" url:"cpuUsagePct"`
	// Memory usage as a percentage (0–100), rounded to two decimal places.
	MemoryUsagePct float64 `json:"memoryUsagePct" url:"memoryUsagePct"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMMetricSampleDto) GetTimestamp() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.Timestamp
}

func (v *VMMetricSampleDto) GetCPUUsagePct() float64 {
	if v == nil {
		return 0
	}
	return v.CPUUsagePct
}

func (v *VMMetricSampleDto) GetMemoryUsagePct() float64 {
	if v == nil {
		return 0
	}
	return v.MemoryUsagePct
}

func (v *VMMetricSampleDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMMetricSampleDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMMetricSampleDto) SetTimestamp(timestamp time.Time) {
	v.Timestamp = timestamp
	v.require(vMMetricSampleDtoFieldTimestamp)
}

// SetCPUUsagePct sets the CPUUsagePct field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMMetricSampleDto) SetCPUUsagePct(cpuUsagePct float64) {
	v.CPUUsagePct = cpuUsagePct
	v.require(vMMetricSampleDtoFieldCPUUsagePct)
}

// SetMemoryUsagePct sets the MemoryUsagePct field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMMetricSampleDto) SetMemoryUsagePct(memoryUsagePct float64) {
	v.MemoryUsagePct = memoryUsagePct
	v.require(vMMetricSampleDtoFieldMemoryUsagePct)
}

func (v *VMMetricSampleDto) UnmarshalJSON(data []byte) error {
	type embed VMMetricSampleDto
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*v),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*v = VMMetricSampleDto(unmarshaler.embed)
	v.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMMetricSampleDto) MarshalJSON() ([]byte, error) {
	type embed VMMetricSampleDto
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*v),
		Timestamp: internal.NewDateTime(v.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMMetricSampleDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vMPasswordResetResponseDtoFieldPassword = big.NewInt(1 << 0)
	vMPasswordResetResponseDtoFieldMessage  = big.NewInt(1 << 1)
)

type VMPasswordResetResponseDto struct {
	// The new VM password. Save this immediately — it will not be returned again.
	Password string `json:"password" url:"password"`
	// Success message with a reminder to save the password.
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMPasswordResetResponseDto) GetPassword() string {
	if v == nil {
		return ""
	}
	return v.Password
}

func (v *VMPasswordResetResponseDto) GetMessage() *string {
	if v == nil {
		return nil
	}
	return v.Message
}

func (v *VMPasswordResetResponseDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMPasswordResetResponseDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMPasswordResetResponseDto) SetPassword(password string) {
	v.Password = password
	v.require(vMPasswordResetResponseDtoFieldPassword)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMPasswordResetResponseDto) SetMessage(message *string) {
	v.Message = message
	v.require(vMPasswordResetResponseDtoFieldMessage)
}

func (v *VMPasswordResetResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VMPasswordResetResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VMPasswordResetResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMPasswordResetResponseDto) MarshalJSON() ([]byte, error) {
	type embed VMPasswordResetResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMPasswordResetResponseDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vMPowerActionResponseDtoFieldID     = big.NewInt(1 << 0)
	vMPowerActionResponseDtoFieldStatus = big.NewInt(1 << 1)
)

type VMPowerActionResponseDto struct {
	// Virtual machine ID.
	ID string `json:"id" url:"id"`
	// Transitional state the VM is moving into.
	Status VMPowerActionResponseDtoStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMPowerActionResponseDto) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VMPowerActionResponseDto) GetStatus() VMPowerActionResponseDtoStatus {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *VMPowerActionResponseDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMPowerActionResponseDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMPowerActionResponseDto) SetID(id string) {
	v.ID = id
	v.require(vMPowerActionResponseDtoFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMPowerActionResponseDto) SetStatus(status VMPowerActionResponseDtoStatus) {
	v.Status = status
	v.require(vMPowerActionResponseDtoFieldStatus)
}

func (v *VMPowerActionResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VMPowerActionResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VMPowerActionResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMPowerActionResponseDto) MarshalJSON() ([]byte, error) {
	type embed VMPowerActionResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMPowerActionResponseDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// Transitional state the VM is moving into.
type VMPowerActionResponseDtoStatus string

const (
	VMPowerActionResponseDtoStatusStarting  VMPowerActionResponseDtoStatus = "starting"
	VMPowerActionResponseDtoStatusStopping  VMPowerActionResponseDtoStatus = "stopping"
	VMPowerActionResponseDtoStatusRebooting VMPowerActionResponseDtoStatus = "rebooting"
)

func NewVMPowerActionResponseDtoStatusFromString(s string) (VMPowerActionResponseDtoStatus, error) {
	switch s {
	case "starting":
		return VMPowerActionResponseDtoStatusStarting, nil
	case "stopping":
		return VMPowerActionResponseDtoStatusStopping, nil
	case "rebooting":
		return VMPowerActionResponseDtoStatusRebooting, nil
	}
	var t VMPowerActionResponseDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v VMPowerActionResponseDtoStatus) Ptr() *VMPowerActionResponseDtoStatus {
	return &v
}

var (
	vMReinstallResponseDtoFieldID     = big.NewInt(1 << 0)
	vMReinstallResponseDtoFieldStatus = big.NewInt(1 << 1)
)

type VMReinstallResponseDto struct {
	// Virtual machine ID.
	ID string `json:"id" url:"id"`
	// Transitional state during reinstall.
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMReinstallResponseDto) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VMReinstallResponseDto) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *VMReinstallResponseDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMReinstallResponseDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMReinstallResponseDto) SetID(id string) {
	v.ID = id
	v.require(vMReinstallResponseDtoFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMReinstallResponseDto) SetStatus(status string) {
	v.Status = status
	v.require(vMReinstallResponseDtoFieldStatus)
}

func (v *VMReinstallResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VMReinstallResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VMReinstallResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMReinstallResponseDto) MarshalJSON() ([]byte, error) {
	type embed VMReinstallResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMReinstallResponseDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vMResponseDtoFieldID                 = big.NewInt(1 << 0)
	vMResponseDtoFieldName               = big.NewInt(1 << 1)
	vMResponseDtoFieldStatus             = big.NewInt(1 << 2)
	vMResponseDtoFieldRegion             = big.NewInt(1 << 3)
	vMResponseDtoFieldVMPackage          = big.NewInt(1 << 4)
	vMResponseDtoFieldCPU                = big.NewInt(1 << 5)
	vMResponseDtoFieldMemoryMb           = big.NewInt(1 << 6)
	vMResponseDtoFieldRootDiskGb         = big.NewInt(1 << 7)
	vMResponseDtoFieldTags               = big.NewInt(1 << 8)
	vMResponseDtoFieldSubscriptionPeriod = big.NewInt(1 << 9)
	vMResponseDtoFieldImage              = big.NewInt(1 << 10)
	vMResponseDtoFieldImageDisplayName   = big.NewInt(1 << 11)
	vMResponseDtoFieldIPAddress          = big.NewInt(1 << 12)
	vMResponseDtoFieldNetworkName        = big.NewInt(1 << 13)
	vMResponseDtoFieldNetworkID          = big.NewInt(1 << 14)
	vMResponseDtoFieldRootVolumeID       = big.NewInt(1 << 15)
	vMResponseDtoFieldCreatedAt          = big.NewInt(1 << 16)
	vMResponseDtoFieldVersionStartedAt   = big.NewInt(1 << 17)
	vMResponseDtoFieldMarketplaceApp     = big.NewInt(1 << 18)
)

type VMResponseDto struct {
	// Unique identifier for this virtual machine.
	ID string `json:"id" url:"id"`
	// Human-readable name for the VM. Shown in dashboards and CLI output.
	Name string `json:"name" url:"name"`
	// Current lifecycle state of the VM.
	Status string `json:"status" url:"status"`
	// Region the VM is provisioned in. References a region label from /v1/compute/regions.
	Region string `json:"region" url:"region"`
	// Package label identifying the CPU/memory/disk preset this VM uses.
	VMPackage *string `json:"vmPackage,omitempty" url:"vmPackage,omitempty"`
	// Number of virtual CPUs allocated to the VM.
	CPU int `json:"cpu" url:"cpu"`
	// Memory allocated to the VM, in megabytes.
	MemoryMb int `json:"memoryMb" url:"memoryMb"`
	// Root disk size, in gigabytes.
	RootDiskGb int `json:"rootDiskGb" url:"rootDiskGb"`
	// Tags assigned to this VM for grouping and filtering.
	Tags []string `json:"tags,omitempty" url:"tags,omitempty"`
	// Billing cadence applied to this VM.
	SubscriptionPeriod string `json:"subscriptionPeriod" url:"subscriptionPeriod"`
	// Image label the VM was provisioned from. References /v1/compute/images.
	Image string `json:"image" url:"image"`
	// Friendly name of the source image.
	ImageDisplayName *string `json:"imageDisplayName,omitempty" url:"imageDisplayName,omitempty"`
	// Primary IP address assigned to the VM on its network.
	IPAddress string `json:"ipAddress" url:"ipAddress"`
	// Name of the network or VPC tier this VM is attached to.
	NetworkName string `json:"networkName" url:"networkName"`
	// Identifier of the network or VPC tier this VM is attached to.
	NetworkID string `json:"networkId" url:"networkId"`
	// Identifier of the VM root volume.
	RootVolumeID string `json:"rootVolumeId" url:"rootVolumeId"`
	// When the VM was first provisioned.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// When the current billing version started (set when the VM is scaled or its disk is resized). Only present if the VM has been modified since creation.
	VersionStartedAt *time.Time `json:"versionStartedAt,omitempty" url:"versionStartedAt,omitempty"`
	// Source marketplace app, when the VM was deployed from one. Absent for OS-only deploys.
	MarketplaceApp *MarketplaceAppDto `json:"marketplaceApp,omitempty" url:"marketplaceApp,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMResponseDto) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VMResponseDto) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *VMResponseDto) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *VMResponseDto) GetRegion() string {
	if v == nil {
		return ""
	}
	return v.Region
}

func (v *VMResponseDto) GetVMPackage() *string {
	if v == nil {
		return nil
	}
	return v.VMPackage
}

func (v *VMResponseDto) GetCPU() int {
	if v == nil {
		return 0
	}
	return v.CPU
}

func (v *VMResponseDto) GetMemoryMb() int {
	if v == nil {
		return 0
	}
	return v.MemoryMb
}

func (v *VMResponseDto) GetRootDiskGb() int {
	if v == nil {
		return 0
	}
	return v.RootDiskGb
}

func (v *VMResponseDto) GetTags() []string {
	if v == nil {
		return nil
	}
	return v.Tags
}

func (v *VMResponseDto) GetSubscriptionPeriod() string {
	if v == nil {
		return ""
	}
	return v.SubscriptionPeriod
}

func (v *VMResponseDto) GetImage() string {
	if v == nil {
		return ""
	}
	return v.Image
}

func (v *VMResponseDto) GetImageDisplayName() *string {
	if v == nil {
		return nil
	}
	return v.ImageDisplayName
}

func (v *VMResponseDto) GetIPAddress() string {
	if v == nil {
		return ""
	}
	return v.IPAddress
}

func (v *VMResponseDto) GetNetworkName() string {
	if v == nil {
		return ""
	}
	return v.NetworkName
}

func (v *VMResponseDto) GetNetworkID() string {
	if v == nil {
		return ""
	}
	return v.NetworkID
}

func (v *VMResponseDto) GetRootVolumeID() string {
	if v == nil {
		return ""
	}
	return v.RootVolumeID
}

func (v *VMResponseDto) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *VMResponseDto) GetVersionStartedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.VersionStartedAt
}

func (v *VMResponseDto) GetMarketplaceApp() *MarketplaceAppDto {
	if v == nil {
		return nil
	}
	return v.MarketplaceApp
}

func (v *VMResponseDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMResponseDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetID(id string) {
	v.ID = id
	v.require(vMResponseDtoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetName(name string) {
	v.Name = name
	v.require(vMResponseDtoFieldName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetStatus(status string) {
	v.Status = status
	v.require(vMResponseDtoFieldStatus)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetRegion(region string) {
	v.Region = region
	v.require(vMResponseDtoFieldRegion)
}

// SetVMPackage sets the VMPackage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetVMPackage(vmPackage *string) {
	v.VMPackage = vmPackage
	v.require(vMResponseDtoFieldVMPackage)
}

// SetCPU sets the CPU field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetCPU(cpu int) {
	v.CPU = cpu
	v.require(vMResponseDtoFieldCPU)
}

// SetMemoryMb sets the MemoryMb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetMemoryMb(memoryMb int) {
	v.MemoryMb = memoryMb
	v.require(vMResponseDtoFieldMemoryMb)
}

// SetRootDiskGb sets the RootDiskGb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetRootDiskGb(rootDiskGb int) {
	v.RootDiskGb = rootDiskGb
	v.require(vMResponseDtoFieldRootDiskGb)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetTags(tags []string) {
	v.Tags = tags
	v.require(vMResponseDtoFieldTags)
}

// SetSubscriptionPeriod sets the SubscriptionPeriod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetSubscriptionPeriod(subscriptionPeriod string) {
	v.SubscriptionPeriod = subscriptionPeriod
	v.require(vMResponseDtoFieldSubscriptionPeriod)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetImage(image string) {
	v.Image = image
	v.require(vMResponseDtoFieldImage)
}

// SetImageDisplayName sets the ImageDisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetImageDisplayName(imageDisplayName *string) {
	v.ImageDisplayName = imageDisplayName
	v.require(vMResponseDtoFieldImageDisplayName)
}

// SetIPAddress sets the IPAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetIPAddress(ipAddress string) {
	v.IPAddress = ipAddress
	v.require(vMResponseDtoFieldIPAddress)
}

// SetNetworkName sets the NetworkName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetNetworkName(networkName string) {
	v.NetworkName = networkName
	v.require(vMResponseDtoFieldNetworkName)
}

// SetNetworkID sets the NetworkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetNetworkID(networkID string) {
	v.NetworkID = networkID
	v.require(vMResponseDtoFieldNetworkID)
}

// SetRootVolumeID sets the RootVolumeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetRootVolumeID(rootVolumeID string) {
	v.RootVolumeID = rootVolumeID
	v.require(vMResponseDtoFieldRootVolumeID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetCreatedAt(createdAt time.Time) {
	v.CreatedAt = createdAt
	v.require(vMResponseDtoFieldCreatedAt)
}

// SetVersionStartedAt sets the VersionStartedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetVersionStartedAt(versionStartedAt *time.Time) {
	v.VersionStartedAt = versionStartedAt
	v.require(vMResponseDtoFieldVersionStartedAt)
}

// SetMarketplaceApp sets the MarketplaceApp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMResponseDto) SetMarketplaceApp(marketplaceApp *MarketplaceAppDto) {
	v.MarketplaceApp = marketplaceApp
	v.require(vMResponseDtoFieldMarketplaceApp)
}

func (v *VMResponseDto) UnmarshalJSON(data []byte) error {
	type embed VMResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt        *internal.DateTime `json:"createdAt"`
		VersionStartedAt *internal.DateTime `json:"versionStartedAt,omitempty"`
	}{
		embed: embed(*v),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*v = VMResponseDto(unmarshaler.embed)
	v.CreatedAt = unmarshaler.CreatedAt.Time()
	v.VersionStartedAt = unmarshaler.VersionStartedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMResponseDto) MarshalJSON() ([]byte, error) {
	type embed VMResponseDto
	var marshaler = struct {
		embed
		CreatedAt        *internal.DateTime `json:"createdAt"`
		VersionStartedAt *internal.DateTime `json:"versionStartedAt,omitempty"`
	}{
		embed:            embed(*v),
		CreatedAt:        internal.NewDateTime(v.CreatedAt),
		VersionStartedAt: internal.NewOptionalDateTime(v.VersionStartedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMResponseDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vMSpecsDtoFieldVcpu       = big.NewInt(1 << 0)
	vMSpecsDtoFieldMemoryMb   = big.NewInt(1 << 1)
	vMSpecsDtoFieldRootDiskGb = big.NewInt(1 << 2)
)

type VMSpecsDto struct {
	// Number of virtual CPUs
	Vcpu float64 `json:"vcpu" url:"vcpu"`
	// Memory in MB
	MemoryMb int `json:"memoryMb" url:"memoryMb"`
	// Root disk size in GB
	RootDiskGb int `json:"rootDiskGb" url:"rootDiskGb"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VMSpecsDto) GetVcpu() float64 {
	if v == nil {
		return 0
	}
	return v.Vcpu
}

func (v *VMSpecsDto) GetMemoryMb() int {
	if v == nil {
		return 0
	}
	return v.MemoryMb
}

func (v *VMSpecsDto) GetRootDiskGb() int {
	if v == nil {
		return 0
	}
	return v.RootDiskGb
}

func (v *VMSpecsDto) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VMSpecsDto) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVcpu sets the Vcpu field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMSpecsDto) SetVcpu(vcpu float64) {
	v.Vcpu = vcpu
	v.require(vMSpecsDtoFieldVcpu)
}

// SetMemoryMb sets the MemoryMb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMSpecsDto) SetMemoryMb(memoryMb int) {
	v.MemoryMb = memoryMb
	v.require(vMSpecsDtoFieldMemoryMb)
}

// SetRootDiskGb sets the RootDiskGb field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VMSpecsDto) SetRootDiskGb(rootDiskGb int) {
	v.RootDiskGb = rootDiskGb
	v.require(vMSpecsDtoFieldRootDiskGb)
}

func (v *VMSpecsDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VMSpecsDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VMSpecsDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VMSpecsDto) MarshalJSON() ([]byte, error) {
	type embed VMSpecsDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VMSpecsDto) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	listVmsResponseFieldTotal = big.NewInt(1 << 0)
	listVmsResponseFieldData  = big.NewInt(1 << 1)
)

type ListVmsResponse struct {
	// Total number of items matching the request, across all pages. Use this together with `pageSize` to compute how many pages exist.
	Total float64          `json:"total" url:"total"`
	Data  []*VMResponseDto `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListVmsResponse) GetTotal() float64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListVmsResponse) GetData() []*VMResponseDto {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListVmsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListVmsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVmsResponse) SetTotal(total float64) {
	l.Total = total
	l.require(listVmsResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVmsResponse) SetData(data []*VMResponseDto) {
	l.Data = data
	l.require(listVmsResponseFieldData)
}

func (l *ListVmsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListVmsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListVmsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListVmsResponse) MarshalJSON() ([]byte, error) {
	type embed ListVmsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListVmsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type PowerVmsRequestAction string

const (
	PowerVmsRequestActionStart  PowerVmsRequestAction = "start"
	PowerVmsRequestActionStop   PowerVmsRequestAction = "stop"
	PowerVmsRequestActionReboot PowerVmsRequestAction = "reboot"
)

func NewPowerVmsRequestActionFromString(s string) (PowerVmsRequestAction, error) {
	switch s {
	case "start":
		return PowerVmsRequestActionStart, nil
	case "stop":
		return PowerVmsRequestActionStop, nil
	case "reboot":
		return PowerVmsRequestActionReboot, nil
	}
	var t PowerVmsRequestAction
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PowerVmsRequestAction) Ptr() *PowerVmsRequestAction {
	return &p
}

var (
	updateHostnameVmsRequestFieldID       = big.NewInt(1 << 0)
	updateHostnameVmsRequestFieldHostname = big.NewInt(1 << 1)
)

type UpdateHostnameVmsRequest struct {
	// ID of the virtual machine
	ID string `json:"-" url:"-"`
	// The new hostname for the virtual machine
	Hostname string `json:"-" url:"hostname"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateHostnameVmsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateHostnameVmsRequest) SetID(id string) {
	u.ID = id
	u.require(updateHostnameVmsRequestFieldID)
}

// SetHostname sets the Hostname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateHostnameVmsRequest) SetHostname(hostname string) {
	u.Hostname = hostname
	u.require(updateHostnameVmsRequestFieldHostname)
}
