// Code generated by Fern. DO NOT EDIT.

package databases

import (
	context "context"
	http "net/http"

	americancloudsdkgo "github.com/American-Cloud/americancloud-sdk-go"
	core "github.com/American-Cloud/americancloud-sdk-go/core"
	internal "github.com/American-Cloud/americancloud-sdk-go/internal"
	option "github.com/American-Cloud/americancloud-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListDatabases(
	ctx context.Context,
	request *americancloudsdkgo.ListDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ListDatabasesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := baseURL + "/api/v1/databases/clusters"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.ListDatabasesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ListDatabasesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateDatabases(
	ctx context.Context,
	request *americancloudsdkgo.CreateDatabaseClusterDto,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.CreateClusterResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := baseURL + "/api/v1/databases/clusters"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *americancloudsdkgo.CreateClusterResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.CreateClusterResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetCostEstimateDatabases(
	ctx context.Context,
	request *americancloudsdkgo.GetCostEstimateDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.DbsCostEstimateResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/cost/%v",
		request.OfferingID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.DbsCostEstimateResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.DbsCostEstimateResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetDatabases(
	ctx context.Context,
	request *americancloudsdkgo.GetDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ClusterDetailResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v",
		request.ClusterID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.ClusterDetailResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ClusterDetailResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteDatabases(
	ctx context.Context,
	request *americancloudsdkgo.DeleteDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ClusterActionResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v",
		request.ClusterID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.ClusterActionResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ClusterActionResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStatusDatabases(
	ctx context.Context,
	request *americancloudsdkgo.GetStatusDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ClusterStatusResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/status",
		request.ClusterID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.ClusterStatusResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ClusterStatusResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetConnectionDatabases(
	ctx context.Context,
	request *americancloudsdkgo.GetConnectionDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ConnectionInfoResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/connection",
		request.ClusterID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.ConnectionInfoResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ConnectionInfoResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetOperationsDatabases(
	ctx context.Context,
	request *americancloudsdkgo.GetOperationsDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.RecentOperationsResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/operations",
		request.ClusterID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.RecentOperationsResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.RecentOperationsResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StartDatabases(
	ctx context.Context,
	request *americancloudsdkgo.StartDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ClusterActionResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/start",
		request.ClusterID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.ClusterActionResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ClusterActionResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StopDatabases(
	ctx context.Context,
	request *americancloudsdkgo.StopDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ClusterActionResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/stop",
		request.ClusterID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *americancloudsdkgo.ClusterActionResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ClusterActionResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ResizeDatabases(
	ctx context.Context,
	request *americancloudsdkgo.ResizeDatabaseClusterDto,
	opts ...option.RequestOption,
) (*core.Response[*americancloudsdkgo.ClusterActionResponseDto], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/resize",
		request.ClusterID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *americancloudsdkgo.ClusterActionResponseDto
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*americancloudsdkgo.ClusterActionResponseDto]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ModifyLoadBalancerDatabases(
	ctx context.Context,
	request *americancloudsdkgo.ModifyLoadBalancerRequestDto,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/load-balancers/%v",
		request.ClusterID,
		request.Type,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) DeleteLoadBalancerDatabases(
	ctx context.Context,
	request *americancloudsdkgo.DeleteLoadBalancerDatabasesRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.americancloud.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/databases/clusters/%v/load-balancers/%v",
		request.ClusterID,
		request.Type,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(americancloudsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}
