// Code generated by Fern. DO NOT EDIT.

package blockstorage

import (
	context "context"

	americancloudsdkgo "github.com/American-Cloud/americancloud-sdk-go"
	core "github.com/American-Cloud/americancloud-sdk-go/core"
	internal "github.com/American-Cloud/americancloud-sdk-go/internal"
	option "github.com/American-Cloud/americancloud-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns block storage volumes for the authenticated account. Optionally filter by virtual machine.
func (c *Client) ListBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.ListBlockStorageRequest,
	opts ...option.RequestOption,
) (*americancloudsdkgo.ListBlockStorageResponse, error) {
	response, err := c.WithRawResponse.ListBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new block storage volume. To preview pricing without creating anything, use POST /storage/block-storage/cost-estimate.
func (c *Client) CreateBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.CreateVolumeDto,
	opts ...option.RequestOption,
) (*americancloudsdkgo.VolumeResponseDto, error) {
	response, err := c.WithRawResponse.CreateBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns details of a specific block storage volume
func (c *Client) GetBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.GetBlockStorageRequest,
	opts ...option.RequestOption,
) (*americancloudsdkgo.VolumeResponseDto, error) {
	response, err := c.WithRawResponse.GetBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a block storage volume. This operation cannot be undone.
func (c *Client) DeleteBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.DeleteBlockStorageRequest,
	opts ...option.RequestOption,
) (*americancloudsdkgo.VolumeDeletionResponseDto, error) {
	response, err := c.WithRawResponse.DeleteBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the estimated cost for a volume with the given specs without creating it. Accepts the same body as create.
func (c *Client) GetCostEstimateBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.CreateVolumeDto,
	opts ...option.RequestOption,
) (*americancloudsdkgo.CostEstimateResponseDto, error) {
	response, err := c.WithRawResponse.GetCostEstimateBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Attaches a volume to a specified virtual machine
func (c *Client) AttachBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.AttachVolumeDto,
	opts ...option.RequestOption,
) (*americancloudsdkgo.VolumeOperationResponseDto, error) {
	response, err := c.WithRawResponse.AttachBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Detaches a volume from its currently attached virtual machine
func (c *Client) DetachBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.DetachBlockStorageRequest,
	opts ...option.RequestOption,
) (*americancloudsdkgo.VolumeOperationResponseDto, error) {
	response, err := c.WithRawResponse.DetachBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Increases the size of a block storage volume. The new size must be larger than the current size.
func (c *Client) ResizeBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.ResizeVolumeDto,
	opts ...option.RequestOption,
) (*americancloudsdkgo.VolumeOperationResponseDto, error) {
	response, err := c.WithRawResponse.ResizeBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns all snapshots for the specified volume.
func (c *Client) ListSnapshotsBlockStorage(
	ctx context.Context,
	request *americancloudsdkgo.ListSnapshotsBlockStorageRequest,
	opts ...option.RequestOption,
) (*americancloudsdkgo.ListSnapshotsBlockStorageResponse, error) {
	response, err := c.WithRawResponse.ListSnapshotsBlockStorage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
