// Code generated by Fern. DO NOT EDIT.

package database_infrastructure_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	americancloudsdkgo "github.com/American-Cloud/americancloud-sdk-go"
	client "github.com/American-Cloud/americancloud-sdk-go/client"
	option "github.com/American-Cloud/americancloud-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestDatabaseInfrastructureListDatabaseInfrastructureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.ListDatabaseInfrastructureRequest{}
	_, invocationErr := client.DatabaseInfrastructure.ListDatabaseInfrastructure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabaseInfrastructureListDatabaseInfrastructureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabaseInfrastructureListDatabaseInfrastructureWithWireMock", "GET", "/api/v1/databases/infrastructure", nil, 1)
}

func TestDatabaseInfrastructureGetDatabaseInfrastructureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.GetDatabaseInfrastructureRequest{
		UserClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	invocationErr := client.DatabaseInfrastructure.GetDatabaseInfrastructure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabaseInfrastructureGetDatabaseInfrastructureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabaseInfrastructureGetDatabaseInfrastructureWithWireMock", "GET", "/api/v1/databases/infrastructure/123e4567-e89b-12d3-a456-426614174000", nil, 1)
}

func TestDatabaseInfrastructureListBackupReposDatabaseInfrastructureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.ListBackupReposDatabaseInfrastructureRequest{
		UserClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.DatabaseInfrastructure.ListBackupReposDatabaseInfrastructure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabaseInfrastructureListBackupReposDatabaseInfrastructureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabaseInfrastructureListBackupReposDatabaseInfrastructureWithWireMock", "GET", "/api/v1/databases/infrastructure/123e4567-e89b-12d3-a456-426614174000/backup-repositories", nil, 1)
}

func TestDatabaseInfrastructureCreateBackupRepoDatabaseInfrastructureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.SetupBackupRepoRequestDto{
		UserClusterID:   "123e4567-e89b-12d3-a456-426614174000",
		RepoName:        "primary-backup-repo",
		Bucket:          "my-storage-bucket",
		Endpoint:        "https://s3.example.com",
		AccessKeyID:     "AKIAIOSFODNN7EXAMPLE",
		AccessKeySecret: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
	}
	_, invocationErr := client.DatabaseInfrastructure.CreateBackupRepoDatabaseInfrastructure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabaseInfrastructureCreateBackupRepoDatabaseInfrastructureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabaseInfrastructureCreateBackupRepoDatabaseInfrastructureWithWireMock", "POST", "/api/v1/databases/infrastructure/123e4567-e89b-12d3-a456-426614174000/backup-repositories", nil, 1)
}

func TestDatabaseInfrastructureUpdateBackupRepoDatabaseInfrastructureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.UpdateBackupRepoRequestDto{
		UserClusterID:   "123e4567-e89b-12d3-a456-426614174000",
		RepoName:        "primary-backup-repo",
		Bucket:          "my-storage-bucket",
		Endpoint:        "https://s3.example.com",
		AccessKeyID:     "AKIAIOSFODNN7EXAMPLE",
		AccessKeySecret: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
	}
	_, invocationErr := client.DatabaseInfrastructure.UpdateBackupRepoDatabaseInfrastructure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabaseInfrastructureUpdateBackupRepoDatabaseInfrastructureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabaseInfrastructureUpdateBackupRepoDatabaseInfrastructureWithWireMock", "PUT", "/api/v1/databases/infrastructure/123e4567-e89b-12d3-a456-426614174000/backup-repositories", nil, 1)
}

func TestDatabaseInfrastructureGetBackupRepoDatabaseInfrastructureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.GetBackupRepoDatabaseInfrastructureRequest{
		UserClusterID: "123e4567-e89b-12d3-a456-426614174000",
		RepoName:      "primary-backup-repo",
	}
	_, invocationErr := client.DatabaseInfrastructure.GetBackupRepoDatabaseInfrastructure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabaseInfrastructureGetBackupRepoDatabaseInfrastructureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabaseInfrastructureGetBackupRepoDatabaseInfrastructureWithWireMock", "GET", "/api/v1/databases/infrastructure/123e4567-e89b-12d3-a456-426614174000/backup-repositories/primary-backup-repo", nil, 1)
}

func TestDatabaseInfrastructureDeleteBackupRepoDatabaseInfrastructureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.DeleteBackupRepoDatabaseInfrastructureRequest{
		UserClusterID: "123e4567-e89b-12d3-a456-426614174000",
		RepoName:      "primary-backup-repo",
	}
	_, invocationErr := client.DatabaseInfrastructure.DeleteBackupRepoDatabaseInfrastructure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabaseInfrastructureDeleteBackupRepoDatabaseInfrastructureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabaseInfrastructureDeleteBackupRepoDatabaseInfrastructureWithWireMock", "DELETE", "/api/v1/databases/infrastructure/123e4567-e89b-12d3-a456-426614174000/backup-repositories/primary-backup-repo", nil, 1)
}
