// Code generated by Fern. DO NOT EDIT.

package databases_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	americancloudsdkgo "github.com/American-Cloud/americancloud-sdk-go"
	client "github.com/American-Cloud/americancloud-sdk-go/client"
	option "github.com/American-Cloud/americancloud-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestDatabasesListDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.ListDatabasesRequest{}
	_, invocationErr := client.Databases.ListDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesListDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesListDatabasesWithWireMock", "GET", "/api/v1/databases/clusters", nil, 1)
}

func TestDatabasesCreateDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.CreateDatabaseClusterDto{
		DbClusterName:    "production-db",
		RegionID:         "123e4567-e89b-12d3-a456-426614174000",
		Tier:             "standard",
		AvailabilityType: americancloudsdkgo.CreateDatabaseClusterDtoAvailabilityTypeSingleNode,
	}
	_, invocationErr := client.Databases.CreateDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesCreateDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesCreateDatabasesWithWireMock", "POST", "/api/v1/databases/clusters", nil, 1)
}

func TestDatabasesGetCostEstimateDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.GetCostEstimateDatabasesRequest{
		OfferingID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.GetCostEstimateDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesGetCostEstimateDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesGetCostEstimateDatabasesWithWireMock", "GET", "/api/v1/databases/clusters/cost/123e4567-e89b-12d3-a456-426614174000", nil, 1)
}

func TestDatabasesGetDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.GetDatabasesRequest{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.GetDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesGetDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesGetDatabasesWithWireMock", "GET", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000", nil, 1)
}

func TestDatabasesDeleteDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.DeleteDatabasesRequest{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.DeleteDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesDeleteDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesDeleteDatabasesWithWireMock", "DELETE", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000", nil, 1)
}

func TestDatabasesGetStatusDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.GetStatusDatabasesRequest{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.GetStatusDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesGetStatusDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesGetStatusDatabasesWithWireMock", "GET", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/status", nil, 1)
}

func TestDatabasesGetConnectionDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.GetConnectionDatabasesRequest{
		ClusterID:       "123e4567-e89b-12d3-a456-426614174000",
		IncludePassword: "includePassword",
	}
	_, invocationErr := client.Databases.GetConnectionDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesGetConnectionDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesGetConnectionDatabasesWithWireMock", "GET", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/connection", map[string]interface{}{"includePassword": "includePassword"}, 1)
}

func TestDatabasesGetOperationsDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.GetOperationsDatabasesRequest{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.GetOperationsDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesGetOperationsDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesGetOperationsDatabasesWithWireMock", "GET", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/operations", nil, 1)
}

func TestDatabasesStartDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.StartDatabasesRequest{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.StartDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesStartDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesStartDatabasesWithWireMock", "POST", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/start", nil, 1)
}

func TestDatabasesStopDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.StopDatabasesRequest{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.StopDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesStopDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesStopDatabasesWithWireMock", "POST", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/stop", nil, 1)
}

func TestDatabasesResizeDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.ResizeDatabaseClusterDto{
		ClusterID:  "123e4567-e89b-12d3-a456-426614174000",
		OfferingID: "123e4567-e89b-12d3-a456-426614174000",
	}
	_, invocationErr := client.Databases.ResizeDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesResizeDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesResizeDatabasesWithWireMock", "POST", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/resize", nil, 1)
}

func TestDatabasesModifyLoadBalancerDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.ModifyLoadBalancerRequestDto{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
		Type:      americancloudsdkgo.ModifyLoadBalancerDatabasesRequestTypePublic,
	}
	invocationErr := client.Databases.ModifyLoadBalancerDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesModifyLoadBalancerDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesModifyLoadBalancerDatabasesWithWireMock", "POST", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/load-balancers/public", nil, 1)
}

func TestDatabasesDeleteLoadBalancerDatabasesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &americancloudsdkgo.DeleteLoadBalancerDatabasesRequest{
		ClusterID: "123e4567-e89b-12d3-a456-426614174000",
		Type:      americancloudsdkgo.DeleteLoadBalancerDatabasesRequestTypePublic,
	}
	invocationErr := client.Databases.DeleteLoadBalancerDatabases(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDatabasesDeleteLoadBalancerDatabasesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDatabasesDeleteLoadBalancerDatabasesWithWireMock", "DELETE", "/api/v1/databases/clusters/123e4567-e89b-12d3-a456-426614174000/load-balancers/public", nil, 1)
}
